<?php

/**
 * PluginAclGroupMemberTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AclGroupMemberTable extends Doctrine_Table
{
	/**
	 * Returns an instance of this class.
	 *
	 * @return object PluginAclGroupMemberTable
	 */
	public static function getInstance()
	{
		return Doctrine_Core::getTable('sfGuardUserGroup');
	}
	/**
	 * Return true if the group has the specified member, otherwise return false
	 * @param integer $group_id
	 * @param integer $member_id
	 * @return true if the group contains the member specified, otherwise return false
	 */
	public static function groupHasMember($group_id,$member_id)
	{
		$q = Doctrine_Query::create()
			->from('sfGuardUserGroup a')
			->andWhere('a.group_id = ?', $group_id)
			->andWhere('a.user_id = ?', $member_id);
		return ($q->fetchOne() ? true : false);
	}
	/**
	 * Get groups for one member
	 * @param integer $member_id
	 * @return Doctrine_Collection
	 */
	public static function groupsByMemberId($member_id)
	{
		$q = Doctrine_Query::create()
			->from('sfGuardUserGroup a')
			->where('a.user_id = ?', $member_id);
		return $q->execute();
	}
	/**
	 * Update acl group list for member
	 * Remove all groups for member and create new list based on $groupsId array
	 * @param integer $member_id
	 * @param array $groupsId
	 */
	public static function updateGroupsIdByMemberId($member_id,array $groupsId)
	{
		$q = Doctrine_Query::create()
			->delete()
			->from('sfGuardUserGroup a')
			->where('a.user_id = ?', $member_id);
		$q->execute();

		foreach($groupsId as $groupId)
		{
			$grMember = new sfGuardUserGroup();
			$grMember->setUserId($member_id);
			$grMember->setGroupId(intval($groupId));
			$grMember->save();
		}
	}
}