<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Activity', 'doctrine');

/**
 * BaseActivity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $libelle
 * @property integer $state
 * @property integer $association_id
 * @property integer $created_by
 * @property integer $updated_by
 * @property Association $Association
 * @property Member $Member
 * @property Member $Member_3
 * @property Doctrine_Collection $Expense
 * @property Doctrine_Collection $Income
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getLibelle()        Returns the current record's "libelle" value
 * @method integer             getState()          Returns the current record's "state" value
 * @method integer             getAssociationId()  Returns the current record's "association_id" value
 * @method integer             getCreatedBy()      Returns the current record's "created_by" value
 * @method integer             getUpdatedBy()      Returns the current record's "updated_by" value
 * @method Association         getAssociation()    Returns the current record's "Association" value
 * @method Member              getMember()         Returns the current record's "Member" value
 * @method Member              getMember3()        Returns the current record's "Member_3" value
 * @method Doctrine_Collection getExpense()        Returns the current record's "Expense" collection
 * @method Doctrine_Collection getIncome()         Returns the current record's "Income" collection
 * @method Activity            setId()             Sets the current record's "id" value
 * @method Activity            setLibelle()        Sets the current record's "libelle" value
 * @method Activity            setState()          Sets the current record's "state" value
 * @method Activity            setAssociationId()  Sets the current record's "association_id" value
 * @method Activity            setCreatedBy()      Sets the current record's "created_by" value
 * @method Activity            setUpdatedBy()      Sets the current record's "updated_by" value
 * @method Activity            setAssociation()    Sets the current record's "Association" value
 * @method Activity            setMember()         Sets the current record's "Member" value
 * @method Activity            setMember3()        Sets the current record's "Member_3" value
 * @method Activity            setExpense()        Sets the current record's "Expense" collection
 * @method Activity            setIncome()         Sets the current record's "Income" collection
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class BaseActivity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('piwam_activity');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('libelle', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('state', 'integer', 1, array(
             'type' => 'integer',
             'default' => '1',
             'length' => '1',
             ));
        $this->hasColumn('association_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('created_by', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('updated_by', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Association', array(
             'local' => 'association_id',
             'foreign' => 'id'));

        $this->hasOne('Member', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('Member as Member_3', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $this->hasMany('Expense', array(
             'local' => 'id',
             'foreign' => 'activity_id'));

        $this->hasMany('Income', array(
             'local' => 'id',
             'foreign' => 'activity_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}