<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Due', 'doctrine');

/**
 * BaseDue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $account_id
 * @property integer $due_type_id
 * @property integer $member_id
 * @property date $date
 * @property decimal $amount
 * @property integer $created_by
 * @property integer $updated_by
 * @property Account $Account
 * @property DueType $DueType
 * @property Member $Member
 * @property Member $Member_4
 * @property Member $Member_5
 * 
 * @method integer getId()          Returns the current record's "id" value
 * @method integer getAccountId()   Returns the current record's "account_id" value
 * @method integer getDueTypeId()   Returns the current record's "due_type_id" value
 * @method integer getMemberId()    Returns the current record's "member_id" value
 * @method date    getDate()        Returns the current record's "date" value
 * @method decimal getAmount()      Returns the current record's "amount" value
 * @method integer getCreatedBy()   Returns the current record's "created_by" value
 * @method integer getUpdatedBy()   Returns the current record's "updated_by" value
 * @method Account getAccount()     Returns the current record's "Account" value
 * @method DueType getDueType()     Returns the current record's "DueType" value
 * @method Member  getMember()      Returns the current record's "Member" value
 * @method Member  getMember4()     Returns the current record's "Member_4" value
 * @method Member  getMember5()     Returns the current record's "Member_5" value
 * @method Due     setId()          Sets the current record's "id" value
 * @method Due     setAccountId()   Sets the current record's "account_id" value
 * @method Due     setDueTypeId()   Sets the current record's "due_type_id" value
 * @method Due     setMemberId()    Sets the current record's "member_id" value
 * @method Due     setDate()        Sets the current record's "date" value
 * @method Due     setAmount()      Sets the current record's "amount" value
 * @method Due     setCreatedBy()   Sets the current record's "created_by" value
 * @method Due     setUpdatedBy()   Sets the current record's "updated_by" value
 * @method Due     setAccount()     Sets the current record's "Account" value
 * @method Due     setDueType()     Sets the current record's "DueType" value
 * @method Due     setMember()      Sets the current record's "Member" value
 * @method Due     setMember4()     Sets the current record's "Member_4" value
 * @method Due     setMember5()     Sets the current record's "Member_5" value
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class BaseDue extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('piwam_due');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('account_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('due_type_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('member_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('date', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => '25',
             ));
        $this->hasColumn('amount', 'decimal', 10, array(
             'type' => 'decimal',
             'notnull' => true,
             'length' => '10',
             'scale' => ' 2',
             ));
        $this->hasColumn('created_by', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('updated_by', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Account', array(
             'local' => 'account_id',
             'foreign' => 'id'));

        $this->hasOne('DueType', array(
             'local' => 'due_type_id',
             'foreign' => 'id'));

        $this->hasOne('Member', array(
             'local' => 'member_id',
             'foreign' => 'id'));

        $this->hasOne('Member as Member_4', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('Member as Member_5', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}