<?php


/**
 * This class defines the structure of the 'piwam_association' table.
 *
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Wed Nov 25 20:26:39 2009
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class AssociationTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.AssociationTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('piwam_association');
		$this->setPhpName('Association');
		$this->setClassname('Association');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('NOM', 'Nom', 'VARCHAR', true, 120, null);
		$this->addColumn('DESCRIPTION', 'Description', 'VARCHAR', false, 255, null);
		$this->addColumn('SITE_WEB', 'SiteWeb', 'VARCHAR', false, 255, null);
		$this->addForeignKey('ENREGISTRE_PAR', 'EnregistrePar', 'INTEGER', 'piwam_membre', 'ID', false, null, null);
		$this->addForeignKey('MIS_A_JOUR_PAR', 'MisAJourPar', 'INTEGER', 'piwam_membre', 'ID', false, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('MembreRelatedByEnregistrePar', 'Membre', RelationMap::MANY_TO_ONE, array('enregistre_par' => 'id', ), 'CASCADE', null);
    $this->addRelation('MembreRelatedByMisAJourPar', 'Membre', RelationMap::MANY_TO_ONE, array('mis_a_jour_par' => 'id', ), 'CASCADE', null);
    $this->addRelation('ConfigValue', 'ConfigValue', RelationMap::ONE_TO_MANY, array('id' => 'association_id', ), null, null);
    $this->addRelation('Activite', 'Activite', RelationMap::ONE_TO_MANY, array('id' => 'association_id', ), 'CASCADE', null);
    $this->addRelation('Compte', 'Compte', RelationMap::ONE_TO_MANY, array('id' => 'association_id', ), 'CASCADE', null);
    $this->addRelation('CotisationType', 'CotisationType', RelationMap::ONE_TO_MANY, array('id' => 'association_id', ), 'CASCADE', null);
    $this->addRelation('Depense', 'Depense', RelationMap::ONE_TO_MANY, array('id' => 'association_id', ), 'CASCADE', null);
    $this->addRelation('Membre', 'Membre', RelationMap::ONE_TO_MANY, array('id' => 'association_id', ), 'CASCADE', null);
    $this->addRelation('Recette', 'Recette', RelationMap::ONE_TO_MANY, array('id' => 'association_id', ), 'CASCADE', null);
    $this->addRelation('Statut', 'Statut', RelationMap::ONE_TO_MANY, array('id' => 'association_id', ), 'CASCADE', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // AssociationTableMap
