<?php


/**
 * This class defines the structure of the 'piwam_cotisation' table.
 *
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Wed Nov 25 20:26:40 2009
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class CotisationTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.CotisationTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('piwam_cotisation');
		$this->setPhpName('Cotisation');
		$this->setClassname('Cotisation');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addForeignKey('COMPTE_ID', 'CompteId', 'INTEGER', 'piwam_compte', 'ID', true, null, null);
		$this->addForeignKey('COTISATION_TYPE_ID', 'CotisationTypeId', 'INTEGER', 'piwam_cotisation_type', 'ID', true, null, null);
		$this->addForeignKey('MEMBRE_ID', 'MembreId', 'INTEGER', 'piwam_membre', 'ID', true, null, null);
		$this->addColumn('DATE', 'Date', 'DATE', true, null, null);
		$this->addForeignKey('ENREGISTRE_PAR', 'EnregistrePar', 'INTEGER', 'piwam_membre', 'ID', true, null, null);
		$this->addColumn('MONTANT', 'Montant', 'DECIMAL', true, 10, null);
		$this->addForeignKey('MIS_A_JOUR_PAR', 'MisAJourPar', 'INTEGER', 'piwam_membre', 'ID', false, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Compte', 'Compte', RelationMap::MANY_TO_ONE, array('compte_id' => 'id', ), 'CASCADE', null);
    $this->addRelation('CotisationType', 'CotisationType', RelationMap::MANY_TO_ONE, array('cotisation_type_id' => 'id', ), 'CASCADE', null);
    $this->addRelation('MembreRelatedByMembreId', 'Membre', RelationMap::MANY_TO_ONE, array('membre_id' => 'id', ), 'CASCADE', null);
    $this->addRelation('MembreRelatedByEnregistrePar', 'Membre', RelationMap::MANY_TO_ONE, array('enregistre_par' => 'id', ), 'CASCADE', null);
    $this->addRelation('MembreRelatedByMisAJourPar', 'Membre', RelationMap::MANY_TO_ONE, array('mis_a_jour_par' => 'id', ), 'CASCADE', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // CotisationTableMap
