<?php

/**
 * Base class that represents a row from the 'cotisation' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Fri May 15 00:05:14 2009
 *
 * @package    lib.model.om
 */
abstract class BaseCotisation extends BaseObject  implements Persistent {


  const PEER = 'CotisationPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        CotisationPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the compte_id field.
	 * @var        int
	 */
	protected $compte_id;

	/**
	 * The value for the cotisation_type_id field.
	 * @var        int
	 */
	protected $cotisation_type_id;

	/**
	 * The value for the membre_id field.
	 * @var        int
	 */
	protected $membre_id;

	/**
	 * The value for the date field.
	 * @var        string
	 */
	protected $date;

	/**
	 * The value for the enregistre_par field.
	 * @var        int
	 */
	protected $enregistre_par;

	/**
	 * The value for the montant field.
	 * @var        string
	 */
	protected $montant;

	/**
	 * The value for the mis_a_jour_par field.
	 * @var        int
	 */
	protected $mis_a_jour_par;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * @var        Compte
	 */
	protected $aCompte;

	/**
	 * @var        CotisationType
	 */
	protected $aCotisationType;

	/**
	 * @var        Membre
	 */
	protected $aMembreRelatedByMembreId;

	/**
	 * @var        Membre
	 */
	protected $aMembreRelatedByEnregistrePar;

	/**
	 * @var        Membre
	 */
	protected $aMembreRelatedByMisAJourPar;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseCotisation object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [compte_id] column value.
	 * 
	 * @return     int
	 */
	public function getCompteId()
	{
		return $this->compte_id;
	}

	/**
	 * Get the [cotisation_type_id] column value.
	 * 
	 * @return     int
	 */
	public function getCotisationTypeId()
	{
		return $this->cotisation_type_id;
	}

	/**
	 * Get the [membre_id] column value.
	 * 
	 * @return     int
	 */
	public function getMembreId()
	{
		return $this->membre_id;
	}

	/**
	 * Get the [optionally formatted] temporal [date] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDate($format = 'Y-m-d')
	{
		if ($this->date === null) {
			return null;
		}


		if ($this->date === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->date);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->date, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [enregistre_par] column value.
	 * 
	 * @return     int
	 */
	public function getEnregistrePar()
	{
		return $this->enregistre_par;
	}

	/**
	 * Get the [montant] column value.
	 * 
	 * @return     string
	 */
	public function getMontant()
	{
		return $this->montant;
	}

	/**
	 * Get the [mis_a_jour_par] column value.
	 * 
	 * @return     int
	 */
	public function getMisAJourPar()
	{
		return $this->mis_a_jour_par;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Cotisation The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = CotisationPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [compte_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Cotisation The current object (for fluent API support)
	 */
	public function setCompteId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->compte_id !== $v) {
			$this->compte_id = $v;
			$this->modifiedColumns[] = CotisationPeer::COMPTE_ID;
		}

		if ($this->aCompte !== null && $this->aCompte->getId() !== $v) {
			$this->aCompte = null;
		}

		return $this;
	} // setCompteId()

	/**
	 * Set the value of [cotisation_type_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Cotisation The current object (for fluent API support)
	 */
	public function setCotisationTypeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->cotisation_type_id !== $v) {
			$this->cotisation_type_id = $v;
			$this->modifiedColumns[] = CotisationPeer::COTISATION_TYPE_ID;
		}

		if ($this->aCotisationType !== null && $this->aCotisationType->getId() !== $v) {
			$this->aCotisationType = null;
		}

		return $this;
	} // setCotisationTypeId()

	/**
	 * Set the value of [membre_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Cotisation The current object (for fluent API support)
	 */
	public function setMembreId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->membre_id !== $v) {
			$this->membre_id = $v;
			$this->modifiedColumns[] = CotisationPeer::MEMBRE_ID;
		}

		if ($this->aMembreRelatedByMembreId !== null && $this->aMembreRelatedByMembreId->getId() !== $v) {
			$this->aMembreRelatedByMembreId = null;
		}

		return $this;
	} // setMembreId()

	/**
	 * Sets the value of [date] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Cotisation The current object (for fluent API support)
	 */
	public function setDate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->date !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->date !== null && $tmpDt = new DateTime($this->date)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->date = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = CotisationPeer::DATE;
			}
		} // if either are not null

		return $this;
	} // setDate()

	/**
	 * Set the value of [enregistre_par] column.
	 * 
	 * @param      int $v new value
	 * @return     Cotisation The current object (for fluent API support)
	 */
	public function setEnregistrePar($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->enregistre_par !== $v) {
			$this->enregistre_par = $v;
			$this->modifiedColumns[] = CotisationPeer::ENREGISTRE_PAR;
		}

		if ($this->aMembreRelatedByEnregistrePar !== null && $this->aMembreRelatedByEnregistrePar->getId() !== $v) {
			$this->aMembreRelatedByEnregistrePar = null;
		}

		return $this;
	} // setEnregistrePar()

	/**
	 * Set the value of [montant] column.
	 * 
	 * @param      string $v new value
	 * @return     Cotisation The current object (for fluent API support)
	 */
	public function setMontant($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->montant !== $v) {
			$this->montant = $v;
			$this->modifiedColumns[] = CotisationPeer::MONTANT;
		}

		return $this;
	} // setMontant()

	/**
	 * Set the value of [mis_a_jour_par] column.
	 * 
	 * @param      int $v new value
	 * @return     Cotisation The current object (for fluent API support)
	 */
	public function setMisAJourPar($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->mis_a_jour_par !== $v) {
			$this->mis_a_jour_par = $v;
			$this->modifiedColumns[] = CotisationPeer::MIS_A_JOUR_PAR;
		}

		if ($this->aMembreRelatedByMisAJourPar !== null && $this->aMembreRelatedByMisAJourPar->getId() !== $v) {
			$this->aMembreRelatedByMisAJourPar = null;
		}

		return $this;
	} // setMisAJourPar()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Cotisation The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = CotisationPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Cotisation The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = CotisationPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->compte_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->cotisation_type_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->membre_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->date = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->enregistre_par = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->montant = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->mis_a_jour_par = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->created_at = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->updated_at = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 10; // 10 = CotisationPeer::NUM_COLUMNS - CotisationPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Cotisation object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aCompte !== null && $this->compte_id !== $this->aCompte->getId()) {
			$this->aCompte = null;
		}
		if ($this->aCotisationType !== null && $this->cotisation_type_id !== $this->aCotisationType->getId()) {
			$this->aCotisationType = null;
		}
		if ($this->aMembreRelatedByMembreId !== null && $this->membre_id !== $this->aMembreRelatedByMembreId->getId()) {
			$this->aMembreRelatedByMembreId = null;
		}
		if ($this->aMembreRelatedByEnregistrePar !== null && $this->enregistre_par !== $this->aMembreRelatedByEnregistrePar->getId()) {
			$this->aMembreRelatedByEnregistrePar = null;
		}
		if ($this->aMembreRelatedByMisAJourPar !== null && $this->mis_a_jour_par !== $this->aMembreRelatedByMisAJourPar->getId()) {
			$this->aMembreRelatedByMisAJourPar = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CotisationPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = CotisationPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aCompte = null;
			$this->aCotisationType = null;
			$this->aMembreRelatedByMembreId = null;
			$this->aMembreRelatedByEnregistrePar = null;
			$this->aMembreRelatedByMisAJourPar = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCotisation:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CotisationPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			CotisationPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseCotisation:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCotisation:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(CotisationPeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

    if ($this->isModified() && !$this->isColumnModified(CotisationPeer::UPDATED_AT))
    {
      $this->setUpdatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CotisationPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseCotisation:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			CotisationPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aCompte !== null) {
				if ($this->aCompte->isModified() || $this->aCompte->isNew()) {
					$affectedRows += $this->aCompte->save($con);
				}
				$this->setCompte($this->aCompte);
			}

			if ($this->aCotisationType !== null) {
				if ($this->aCotisationType->isModified() || $this->aCotisationType->isNew()) {
					$affectedRows += $this->aCotisationType->save($con);
				}
				$this->setCotisationType($this->aCotisationType);
			}

			if ($this->aMembreRelatedByMembreId !== null) {
				if ($this->aMembreRelatedByMembreId->isModified() || $this->aMembreRelatedByMembreId->isNew()) {
					$affectedRows += $this->aMembreRelatedByMembreId->save($con);
				}
				$this->setMembreRelatedByMembreId($this->aMembreRelatedByMembreId);
			}

			if ($this->aMembreRelatedByEnregistrePar !== null) {
				if ($this->aMembreRelatedByEnregistrePar->isModified() || $this->aMembreRelatedByEnregistrePar->isNew()) {
					$affectedRows += $this->aMembreRelatedByEnregistrePar->save($con);
				}
				$this->setMembreRelatedByEnregistrePar($this->aMembreRelatedByEnregistrePar);
			}

			if ($this->aMembreRelatedByMisAJourPar !== null) {
				if ($this->aMembreRelatedByMisAJourPar->isModified() || $this->aMembreRelatedByMisAJourPar->isNew()) {
					$affectedRows += $this->aMembreRelatedByMisAJourPar->save($con);
				}
				$this->setMembreRelatedByMisAJourPar($this->aMembreRelatedByMisAJourPar);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = CotisationPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = CotisationPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += CotisationPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aCompte !== null) {
				if (!$this->aCompte->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aCompte->getValidationFailures());
				}
			}

			if ($this->aCotisationType !== null) {
				if (!$this->aCotisationType->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aCotisationType->getValidationFailures());
				}
			}

			if ($this->aMembreRelatedByMembreId !== null) {
				if (!$this->aMembreRelatedByMembreId->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aMembreRelatedByMembreId->getValidationFailures());
				}
			}

			if ($this->aMembreRelatedByEnregistrePar !== null) {
				if (!$this->aMembreRelatedByEnregistrePar->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aMembreRelatedByEnregistrePar->getValidationFailures());
				}
			}

			if ($this->aMembreRelatedByMisAJourPar !== null) {
				if (!$this->aMembreRelatedByMisAJourPar->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aMembreRelatedByMisAJourPar->getValidationFailures());
				}
			}


			if (($retval = CotisationPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = CotisationPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getCompteId();
				break;
			case 2:
				return $this->getCotisationTypeId();
				break;
			case 3:
				return $this->getMembreId();
				break;
			case 4:
				return $this->getDate();
				break;
			case 5:
				return $this->getEnregistrePar();
				break;
			case 6:
				return $this->getMontant();
				break;
			case 7:
				return $this->getMisAJourPar();
				break;
			case 8:
				return $this->getCreatedAt();
				break;
			case 9:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = CotisationPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getCompteId(),
			$keys[2] => $this->getCotisationTypeId(),
			$keys[3] => $this->getMembreId(),
			$keys[4] => $this->getDate(),
			$keys[5] => $this->getEnregistrePar(),
			$keys[6] => $this->getMontant(),
			$keys[7] => $this->getMisAJourPar(),
			$keys[8] => $this->getCreatedAt(),
			$keys[9] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = CotisationPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setCompteId($value);
				break;
			case 2:
				$this->setCotisationTypeId($value);
				break;
			case 3:
				$this->setMembreId($value);
				break;
			case 4:
				$this->setDate($value);
				break;
			case 5:
				$this->setEnregistrePar($value);
				break;
			case 6:
				$this->setMontant($value);
				break;
			case 7:
				$this->setMisAJourPar($value);
				break;
			case 8:
				$this->setCreatedAt($value);
				break;
			case 9:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = CotisationPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setCompteId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setCotisationTypeId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setMembreId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setDate($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setEnregistrePar($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setMontant($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setMisAJourPar($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setCreatedAt($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setUpdatedAt($arr[$keys[9]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(CotisationPeer::DATABASE_NAME);

		if ($this->isColumnModified(CotisationPeer::ID)) $criteria->add(CotisationPeer::ID, $this->id);
		if ($this->isColumnModified(CotisationPeer::COMPTE_ID)) $criteria->add(CotisationPeer::COMPTE_ID, $this->compte_id);
		if ($this->isColumnModified(CotisationPeer::COTISATION_TYPE_ID)) $criteria->add(CotisationPeer::COTISATION_TYPE_ID, $this->cotisation_type_id);
		if ($this->isColumnModified(CotisationPeer::MEMBRE_ID)) $criteria->add(CotisationPeer::MEMBRE_ID, $this->membre_id);
		if ($this->isColumnModified(CotisationPeer::DATE)) $criteria->add(CotisationPeer::DATE, $this->date);
		if ($this->isColumnModified(CotisationPeer::ENREGISTRE_PAR)) $criteria->add(CotisationPeer::ENREGISTRE_PAR, $this->enregistre_par);
		if ($this->isColumnModified(CotisationPeer::MONTANT)) $criteria->add(CotisationPeer::MONTANT, $this->montant);
		if ($this->isColumnModified(CotisationPeer::MIS_A_JOUR_PAR)) $criteria->add(CotisationPeer::MIS_A_JOUR_PAR, $this->mis_a_jour_par);
		if ($this->isColumnModified(CotisationPeer::CREATED_AT)) $criteria->add(CotisationPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(CotisationPeer::UPDATED_AT)) $criteria->add(CotisationPeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(CotisationPeer::DATABASE_NAME);

		$criteria->add(CotisationPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Cotisation (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setCompteId($this->compte_id);

		$copyObj->setCotisationTypeId($this->cotisation_type_id);

		$copyObj->setMembreId($this->membre_id);

		$copyObj->setDate($this->date);

		$copyObj->setEnregistrePar($this->enregistre_par);

		$copyObj->setMontant($this->montant);

		$copyObj->setMisAJourPar($this->mis_a_jour_par);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Cotisation Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     CotisationPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new CotisationPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Compte object.
	 *
	 * @param      Compte $v
	 * @return     Cotisation The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setCompte(Compte $v = null)
	{
		if ($v === null) {
			$this->setCompteId(NULL);
		} else {
			$this->setCompteId($v->getId());
		}

		$this->aCompte = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Compte object, it will not be re-added.
		if ($v !== null) {
			$v->addCotisation($this);
		}

		return $this;
	}


	/**
	 * Get the associated Compte object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Compte The associated Compte object.
	 * @throws     PropelException
	 */
	public function getCompte(PropelPDO $con = null)
	{
		if ($this->aCompte === null && ($this->compte_id !== null)) {
			$c = new Criteria(ComptePeer::DATABASE_NAME);
			$c->add(ComptePeer::ID, $this->compte_id);
			$this->aCompte = ComptePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aCompte->addCotisations($this);
			 */
		}
		return $this->aCompte;
	}

	/**
	 * Declares an association between this object and a CotisationType object.
	 *
	 * @param      CotisationType $v
	 * @return     Cotisation The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setCotisationType(CotisationType $v = null)
	{
		if ($v === null) {
			$this->setCotisationTypeId(NULL);
		} else {
			$this->setCotisationTypeId($v->getId());
		}

		$this->aCotisationType = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the CotisationType object, it will not be re-added.
		if ($v !== null) {
			$v->addCotisation($this);
		}

		return $this;
	}


	/**
	 * Get the associated CotisationType object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     CotisationType The associated CotisationType object.
	 * @throws     PropelException
	 */
	public function getCotisationType(PropelPDO $con = null)
	{
		if ($this->aCotisationType === null && ($this->cotisation_type_id !== null)) {
			$c = new Criteria(CotisationTypePeer::DATABASE_NAME);
			$c->add(CotisationTypePeer::ID, $this->cotisation_type_id);
			$this->aCotisationType = CotisationTypePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aCotisationType->addCotisations($this);
			 */
		}
		return $this->aCotisationType;
	}

	/**
	 * Declares an association between this object and a Membre object.
	 *
	 * @param      Membre $v
	 * @return     Cotisation The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setMembreRelatedByMembreId(Membre $v = null)
	{
		if ($v === null) {
			$this->setMembreId(NULL);
		} else {
			$this->setMembreId($v->getId());
		}

		$this->aMembreRelatedByMembreId = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Membre object, it will not be re-added.
		if ($v !== null) {
			$v->addCotisationRelatedByMembreId($this);
		}

		return $this;
	}


	/**
	 * Get the associated Membre object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Membre The associated Membre object.
	 * @throws     PropelException
	 */
	public function getMembreRelatedByMembreId(PropelPDO $con = null)
	{
		if ($this->aMembreRelatedByMembreId === null && ($this->membre_id !== null)) {
			$c = new Criteria(MembrePeer::DATABASE_NAME);
			$c->add(MembrePeer::ID, $this->membre_id);
			$this->aMembreRelatedByMembreId = MembrePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aMembreRelatedByMembreId->addCotisationsRelatedByMembreId($this);
			 */
		}
		return $this->aMembreRelatedByMembreId;
	}

	/**
	 * Declares an association between this object and a Membre object.
	 *
	 * @param      Membre $v
	 * @return     Cotisation The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setMembreRelatedByEnregistrePar(Membre $v = null)
	{
		if ($v === null) {
			$this->setEnregistrePar(NULL);
		} else {
			$this->setEnregistrePar($v->getId());
		}

		$this->aMembreRelatedByEnregistrePar = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Membre object, it will not be re-added.
		if ($v !== null) {
			$v->addCotisationRelatedByEnregistrePar($this);
		}

		return $this;
	}


	/**
	 * Get the associated Membre object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Membre The associated Membre object.
	 * @throws     PropelException
	 */
	public function getMembreRelatedByEnregistrePar(PropelPDO $con = null)
	{
		if ($this->aMembreRelatedByEnregistrePar === null && ($this->enregistre_par !== null)) {
			$c = new Criteria(MembrePeer::DATABASE_NAME);
			$c->add(MembrePeer::ID, $this->enregistre_par);
			$this->aMembreRelatedByEnregistrePar = MembrePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aMembreRelatedByEnregistrePar->addCotisationsRelatedByEnregistrePar($this);
			 */
		}
		return $this->aMembreRelatedByEnregistrePar;
	}

	/**
	 * Declares an association between this object and a Membre object.
	 *
	 * @param      Membre $v
	 * @return     Cotisation The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setMembreRelatedByMisAJourPar(Membre $v = null)
	{
		if ($v === null) {
			$this->setMisAJourPar(NULL);
		} else {
			$this->setMisAJourPar($v->getId());
		}

		$this->aMembreRelatedByMisAJourPar = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Membre object, it will not be re-added.
		if ($v !== null) {
			$v->addCotisationRelatedByMisAJourPar($this);
		}

		return $this;
	}


	/**
	 * Get the associated Membre object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Membre The associated Membre object.
	 * @throws     PropelException
	 */
	public function getMembreRelatedByMisAJourPar(PropelPDO $con = null)
	{
		if ($this->aMembreRelatedByMisAJourPar === null && ($this->mis_a_jour_par !== null)) {
			$c = new Criteria(MembrePeer::DATABASE_NAME);
			$c->add(MembrePeer::ID, $this->mis_a_jour_par);
			$this->aMembreRelatedByMisAJourPar = MembrePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aMembreRelatedByMisAJourPar->addCotisationsRelatedByMisAJourPar($this);
			 */
		}
		return $this->aMembreRelatedByMisAJourPar;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aCompte = null;
			$this->aCotisationType = null;
			$this->aMembreRelatedByMembreId = null;
			$this->aMembreRelatedByEnregistrePar = null;
			$this->aMembreRelatedByMisAJourPar = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseCotisation:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseCotisation::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseCotisation
