<?php

/**
 * Base class that represents a row from the 'compte' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Fri May 15 00:05:14 2009
 *
 * @package    lib.model.om
 */
abstract class BaseCompte extends BaseObject  implements Persistent {


  const PEER = 'ComptePeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ComptePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the libelle field.
	 * @var        string
	 */
	protected $libelle;

	/**
	 * The value for the association_id field.
	 * @var        int
	 */
	protected $association_id;

	/**
	 * The value for the reference field.
	 * @var        string
	 */
	protected $reference;

	/**
	 * The value for the actif field.
	 * Note: this column has a database default value of: true
	 * @var        boolean
	 */
	protected $actif;

	/**
	 * The value for the enregistre_par field.
	 * @var        int
	 */
	protected $enregistre_par;

	/**
	 * The value for the mis_a_jour_par field.
	 * @var        int
	 */
	protected $mis_a_jour_par;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * @var        Association
	 */
	protected $aAssociation;

	/**
	 * @var        Membre
	 */
	protected $aMembreRelatedByEnregistrePar;

	/**
	 * @var        Membre
	 */
	protected $aMembreRelatedByMisAJourPar;

	/**
	 * @var        array Cotisation[] Collection to store aggregation of Cotisation objects.
	 */
	protected $collCotisations;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCotisations.
	 */
	private $lastCotisationCriteria = null;

	/**
	 * @var        array Depense[] Collection to store aggregation of Depense objects.
	 */
	protected $collDepenses;

	/**
	 * @var        Criteria The criteria used to select the current contents of collDepenses.
	 */
	private $lastDepenseCriteria = null;

	/**
	 * @var        array Recette[] Collection to store aggregation of Recette objects.
	 */
	protected $collRecettes;

	/**
	 * @var        Criteria The criteria used to select the current contents of collRecettes.
	 */
	private $lastRecetteCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseCompte object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->actif = true;
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [libelle] column value.
	 * 
	 * @return     string
	 */
	public function getLibelle()
	{
		return $this->libelle;
	}

	/**
	 * Get the [association_id] column value.
	 * 
	 * @return     int
	 */
	public function getAssociationId()
	{
		return $this->association_id;
	}

	/**
	 * Get the [reference] column value.
	 * 
	 * @return     string
	 */
	public function getReference()
	{
		return $this->reference;
	}

	/**
	 * Get the [actif] column value.
	 * 
	 * @return     boolean
	 */
	public function getActif()
	{
		return $this->actif;
	}

	/**
	 * Get the [enregistre_par] column value.
	 * 
	 * @return     int
	 */
	public function getEnregistrePar()
	{
		return $this->enregistre_par;
	}

	/**
	 * Get the [mis_a_jour_par] column value.
	 * 
	 * @return     int
	 */
	public function getMisAJourPar()
	{
		return $this->mis_a_jour_par;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Compte The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = ComptePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [libelle] column.
	 * 
	 * @param      string $v new value
	 * @return     Compte The current object (for fluent API support)
	 */
	public function setLibelle($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->libelle !== $v) {
			$this->libelle = $v;
			$this->modifiedColumns[] = ComptePeer::LIBELLE;
		}

		return $this;
	} // setLibelle()

	/**
	 * Set the value of [association_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Compte The current object (for fluent API support)
	 */
	public function setAssociationId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->association_id !== $v) {
			$this->association_id = $v;
			$this->modifiedColumns[] = ComptePeer::ASSOCIATION_ID;
		}

		if ($this->aAssociation !== null && $this->aAssociation->getId() !== $v) {
			$this->aAssociation = null;
		}

		return $this;
	} // setAssociationId()

	/**
	 * Set the value of [reference] column.
	 * 
	 * @param      string $v new value
	 * @return     Compte The current object (for fluent API support)
	 */
	public function setReference($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->reference !== $v) {
			$this->reference = $v;
			$this->modifiedColumns[] = ComptePeer::REFERENCE;
		}

		return $this;
	} // setReference()

	/**
	 * Set the value of [actif] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Compte The current object (for fluent API support)
	 */
	public function setActif($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->actif !== $v || $v === true) {
			$this->actif = $v;
			$this->modifiedColumns[] = ComptePeer::ACTIF;
		}

		return $this;
	} // setActif()

	/**
	 * Set the value of [enregistre_par] column.
	 * 
	 * @param      int $v new value
	 * @return     Compte The current object (for fluent API support)
	 */
	public function setEnregistrePar($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->enregistre_par !== $v) {
			$this->enregistre_par = $v;
			$this->modifiedColumns[] = ComptePeer::ENREGISTRE_PAR;
		}

		if ($this->aMembreRelatedByEnregistrePar !== null && $this->aMembreRelatedByEnregistrePar->getId() !== $v) {
			$this->aMembreRelatedByEnregistrePar = null;
		}

		return $this;
	} // setEnregistrePar()

	/**
	 * Set the value of [mis_a_jour_par] column.
	 * 
	 * @param      int $v new value
	 * @return     Compte The current object (for fluent API support)
	 */
	public function setMisAJourPar($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->mis_a_jour_par !== $v) {
			$this->mis_a_jour_par = $v;
			$this->modifiedColumns[] = ComptePeer::MIS_A_JOUR_PAR;
		}

		if ($this->aMembreRelatedByMisAJourPar !== null && $this->aMembreRelatedByMisAJourPar->getId() !== $v) {
			$this->aMembreRelatedByMisAJourPar = null;
		}

		return $this;
	} // setMisAJourPar()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Compte The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = ComptePeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Compte The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = ComptePeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(ComptePeer::ACTIF))) {
				return false;
			}

			if ($this->actif !== true) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->libelle = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->association_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->reference = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->actif = ($row[$startcol + 4] !== null) ? (boolean) $row[$startcol + 4] : null;
			$this->enregistre_par = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->mis_a_jour_par = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->created_at = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->updated_at = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 9; // 9 = ComptePeer::NUM_COLUMNS - ComptePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Compte object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aAssociation !== null && $this->association_id !== $this->aAssociation->getId()) {
			$this->aAssociation = null;
		}
		if ($this->aMembreRelatedByEnregistrePar !== null && $this->enregistre_par !== $this->aMembreRelatedByEnregistrePar->getId()) {
			$this->aMembreRelatedByEnregistrePar = null;
		}
		if ($this->aMembreRelatedByMisAJourPar !== null && $this->mis_a_jour_par !== $this->aMembreRelatedByMisAJourPar->getId()) {
			$this->aMembreRelatedByMisAJourPar = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ComptePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ComptePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aAssociation = null;
			$this->aMembreRelatedByEnregistrePar = null;
			$this->aMembreRelatedByMisAJourPar = null;
			$this->collCotisations = null;
			$this->lastCotisationCriteria = null;

			$this->collDepenses = null;
			$this->lastDepenseCriteria = null;

			$this->collRecettes = null;
			$this->lastRecetteCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCompte:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ComptePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			ComptePeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseCompte:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCompte:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(ComptePeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

    if ($this->isModified() && !$this->isColumnModified(ComptePeer::UPDATED_AT))
    {
      $this->setUpdatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ComptePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseCompte:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			ComptePeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aAssociation !== null) {
				if ($this->aAssociation->isModified() || $this->aAssociation->isNew()) {
					$affectedRows += $this->aAssociation->save($con);
				}
				$this->setAssociation($this->aAssociation);
			}

			if ($this->aMembreRelatedByEnregistrePar !== null) {
				if ($this->aMembreRelatedByEnregistrePar->isModified() || $this->aMembreRelatedByEnregistrePar->isNew()) {
					$affectedRows += $this->aMembreRelatedByEnregistrePar->save($con);
				}
				$this->setMembreRelatedByEnregistrePar($this->aMembreRelatedByEnregistrePar);
			}

			if ($this->aMembreRelatedByMisAJourPar !== null) {
				if ($this->aMembreRelatedByMisAJourPar->isModified() || $this->aMembreRelatedByMisAJourPar->isNew()) {
					$affectedRows += $this->aMembreRelatedByMisAJourPar->save($con);
				}
				$this->setMembreRelatedByMisAJourPar($this->aMembreRelatedByMisAJourPar);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = ComptePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ComptePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += ComptePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collCotisations !== null) {
				foreach ($this->collCotisations as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collDepenses !== null) {
				foreach ($this->collDepenses as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collRecettes !== null) {
				foreach ($this->collRecettes as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aAssociation !== null) {
				if (!$this->aAssociation->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aAssociation->getValidationFailures());
				}
			}

			if ($this->aMembreRelatedByEnregistrePar !== null) {
				if (!$this->aMembreRelatedByEnregistrePar->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aMembreRelatedByEnregistrePar->getValidationFailures());
				}
			}

			if ($this->aMembreRelatedByMisAJourPar !== null) {
				if (!$this->aMembreRelatedByMisAJourPar->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aMembreRelatedByMisAJourPar->getValidationFailures());
				}
			}


			if (($retval = ComptePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collCotisations !== null) {
					foreach ($this->collCotisations as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collDepenses !== null) {
					foreach ($this->collDepenses as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collRecettes !== null) {
					foreach ($this->collRecettes as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ComptePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getLibelle();
				break;
			case 2:
				return $this->getAssociationId();
				break;
			case 3:
				return $this->getReference();
				break;
			case 4:
				return $this->getActif();
				break;
			case 5:
				return $this->getEnregistrePar();
				break;
			case 6:
				return $this->getMisAJourPar();
				break;
			case 7:
				return $this->getCreatedAt();
				break;
			case 8:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = ComptePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getLibelle(),
			$keys[2] => $this->getAssociationId(),
			$keys[3] => $this->getReference(),
			$keys[4] => $this->getActif(),
			$keys[5] => $this->getEnregistrePar(),
			$keys[6] => $this->getMisAJourPar(),
			$keys[7] => $this->getCreatedAt(),
			$keys[8] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ComptePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setLibelle($value);
				break;
			case 2:
				$this->setAssociationId($value);
				break;
			case 3:
				$this->setReference($value);
				break;
			case 4:
				$this->setActif($value);
				break;
			case 5:
				$this->setEnregistrePar($value);
				break;
			case 6:
				$this->setMisAJourPar($value);
				break;
			case 7:
				$this->setCreatedAt($value);
				break;
			case 8:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ComptePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setLibelle($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setAssociationId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setReference($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setActif($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setEnregistrePar($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setMisAJourPar($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setCreatedAt($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setUpdatedAt($arr[$keys[8]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ComptePeer::DATABASE_NAME);

		if ($this->isColumnModified(ComptePeer::ID)) $criteria->add(ComptePeer::ID, $this->id);
		if ($this->isColumnModified(ComptePeer::LIBELLE)) $criteria->add(ComptePeer::LIBELLE, $this->libelle);
		if ($this->isColumnModified(ComptePeer::ASSOCIATION_ID)) $criteria->add(ComptePeer::ASSOCIATION_ID, $this->association_id);
		if ($this->isColumnModified(ComptePeer::REFERENCE)) $criteria->add(ComptePeer::REFERENCE, $this->reference);
		if ($this->isColumnModified(ComptePeer::ACTIF)) $criteria->add(ComptePeer::ACTIF, $this->actif);
		if ($this->isColumnModified(ComptePeer::ENREGISTRE_PAR)) $criteria->add(ComptePeer::ENREGISTRE_PAR, $this->enregistre_par);
		if ($this->isColumnModified(ComptePeer::MIS_A_JOUR_PAR)) $criteria->add(ComptePeer::MIS_A_JOUR_PAR, $this->mis_a_jour_par);
		if ($this->isColumnModified(ComptePeer::CREATED_AT)) $criteria->add(ComptePeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(ComptePeer::UPDATED_AT)) $criteria->add(ComptePeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ComptePeer::DATABASE_NAME);

		$criteria->add(ComptePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Compte (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setLibelle($this->libelle);

		$copyObj->setAssociationId($this->association_id);

		$copyObj->setReference($this->reference);

		$copyObj->setActif($this->actif);

		$copyObj->setEnregistrePar($this->enregistre_par);

		$copyObj->setMisAJourPar($this->mis_a_jour_par);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getCotisations() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addCotisation($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getDepenses() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addDepense($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getRecettes() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addRecette($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Compte Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ComptePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ComptePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Association object.
	 *
	 * @param      Association $v
	 * @return     Compte The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setAssociation(Association $v = null)
	{
		if ($v === null) {
			$this->setAssociationId(NULL);
		} else {
			$this->setAssociationId($v->getId());
		}

		$this->aAssociation = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Association object, it will not be re-added.
		if ($v !== null) {
			$v->addCompte($this);
		}

		return $this;
	}


	/**
	 * Get the associated Association object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Association The associated Association object.
	 * @throws     PropelException
	 */
	public function getAssociation(PropelPDO $con = null)
	{
		if ($this->aAssociation === null && ($this->association_id !== null)) {
			$c = new Criteria(AssociationPeer::DATABASE_NAME);
			$c->add(AssociationPeer::ID, $this->association_id);
			$this->aAssociation = AssociationPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aAssociation->addComptes($this);
			 */
		}
		return $this->aAssociation;
	}

	/**
	 * Declares an association between this object and a Membre object.
	 *
	 * @param      Membre $v
	 * @return     Compte The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setMembreRelatedByEnregistrePar(Membre $v = null)
	{
		if ($v === null) {
			$this->setEnregistrePar(NULL);
		} else {
			$this->setEnregistrePar($v->getId());
		}

		$this->aMembreRelatedByEnregistrePar = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Membre object, it will not be re-added.
		if ($v !== null) {
			$v->addCompteRelatedByEnregistrePar($this);
		}

		return $this;
	}


	/**
	 * Get the associated Membre object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Membre The associated Membre object.
	 * @throws     PropelException
	 */
	public function getMembreRelatedByEnregistrePar(PropelPDO $con = null)
	{
		if ($this->aMembreRelatedByEnregistrePar === null && ($this->enregistre_par !== null)) {
			$c = new Criteria(MembrePeer::DATABASE_NAME);
			$c->add(MembrePeer::ID, $this->enregistre_par);
			$this->aMembreRelatedByEnregistrePar = MembrePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aMembreRelatedByEnregistrePar->addComptesRelatedByEnregistrePar($this);
			 */
		}
		return $this->aMembreRelatedByEnregistrePar;
	}

	/**
	 * Declares an association between this object and a Membre object.
	 *
	 * @param      Membre $v
	 * @return     Compte The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setMembreRelatedByMisAJourPar(Membre $v = null)
	{
		if ($v === null) {
			$this->setMisAJourPar(NULL);
		} else {
			$this->setMisAJourPar($v->getId());
		}

		$this->aMembreRelatedByMisAJourPar = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Membre object, it will not be re-added.
		if ($v !== null) {
			$v->addCompteRelatedByMisAJourPar($this);
		}

		return $this;
	}


	/**
	 * Get the associated Membre object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Membre The associated Membre object.
	 * @throws     PropelException
	 */
	public function getMembreRelatedByMisAJourPar(PropelPDO $con = null)
	{
		if ($this->aMembreRelatedByMisAJourPar === null && ($this->mis_a_jour_par !== null)) {
			$c = new Criteria(MembrePeer::DATABASE_NAME);
			$c->add(MembrePeer::ID, $this->mis_a_jour_par);
			$this->aMembreRelatedByMisAJourPar = MembrePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aMembreRelatedByMisAJourPar->addComptesRelatedByMisAJourPar($this);
			 */
		}
		return $this->aMembreRelatedByMisAJourPar;
	}

	/**
	 * Clears out the collCotisations collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCotisations()
	 */
	public function clearCotisations()
	{
		$this->collCotisations = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCotisations collection (array).
	 *
	 * By default this just sets the collCotisations collection to an empty array (like clearcollCotisations());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCotisations()
	{
		$this->collCotisations = array();
	}

	/**
	 * Gets an array of Cotisation objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Compte has previously been saved, it will retrieve
	 * related Cotisations from storage. If this Compte is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Cotisation[]
	 * @throws     PropelException
	 */
	public function getCotisations($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ComptePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCotisations === null) {
			if ($this->isNew()) {
			   $this->collCotisations = array();
			} else {

				$criteria->add(CotisationPeer::COMPTE_ID, $this->id);

				CotisationPeer::addSelectColumns($criteria);
				$this->collCotisations = CotisationPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(CotisationPeer::COMPTE_ID, $this->id);

				CotisationPeer::addSelectColumns($criteria);
				if (!isset($this->lastCotisationCriteria) || !$this->lastCotisationCriteria->equals($criteria)) {
					$this->collCotisations = CotisationPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCotisationCriteria = $criteria;
		return $this->collCotisations;
	}

	/**
	 * Returns the number of related Cotisation objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Cotisation objects.
	 * @throws     PropelException
	 */
	public function countCotisations(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ComptePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCotisations === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(CotisationPeer::COMPTE_ID, $this->id);

				$count = CotisationPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(CotisationPeer::COMPTE_ID, $this->id);

				if (!isset($this->lastCotisationCriteria) || !$this->lastCotisationCriteria->equals($criteria)) {
					$count = CotisationPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collCotisations);
				}
			} else {
				$count = count($this->collCotisations);
			}
		}
		$this->lastCotisationCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a Cotisation object to this object
	 * through the Cotisation foreign key attribute.
	 *
	 * @param      Cotisation $l Cotisation
	 * @return     void
	 * @throws     PropelException
	 */
	public function addCotisation(Cotisation $l)
	{
		if ($this->collCotisations === null) {
			$this->initCotisations();
		}
		if (!in_array($l, $this->collCotisations, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCotisations, $l);
			$l->setCompte($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Compte is new, it will return
	 * an empty collection; or if this Compte has previously
	 * been saved, it will retrieve related Cotisations from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Compte.
	 */
	public function getCotisationsJoinCotisationType($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ComptePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCotisations === null) {
			if ($this->isNew()) {
				$this->collCotisations = array();
			} else {

				$criteria->add(CotisationPeer::COMPTE_ID, $this->id);

				$this->collCotisations = CotisationPeer::doSelectJoinCotisationType($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CotisationPeer::COMPTE_ID, $this->id);

			if (!isset($this->lastCotisationCriteria) || !$this->lastCotisationCriteria->equals($criteria)) {
				$this->collCotisations = CotisationPeer::doSelectJoinCotisationType($criteria, $con, $join_behavior);
			}
		}
		$this->lastCotisationCriteria = $criteria;

		return $this->collCotisations;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Compte is new, it will return
	 * an empty collection; or if this Compte has previously
	 * been saved, it will retrieve related Cotisations from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Compte.
	 */
	public function getCotisationsJoinMembreRelatedByMembreId($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ComptePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCotisations === null) {
			if ($this->isNew()) {
				$this->collCotisations = array();
			} else {

				$criteria->add(CotisationPeer::COMPTE_ID, $this->id);

				$this->collCotisations = CotisationPeer::doSelectJoinMembreRelatedByMembreId($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CotisationPeer::COMPTE_ID, $this->id);

			if (!isset($this->lastCotisationCriteria) || !$this->lastCotisationCriteria->equals($criteria)) {
				$this->collCotisations = CotisationPeer::doSelectJoinMembreRelatedByMembreId($criteria, $con, $join_behavior);
			}
		}
		$this->lastCotisationCriteria = $criteria;

		return $this->collCotisations;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Compte is new, it will return
	 * an empty collection; or if this Compte has previously
	 * been saved, it will retrieve related Cotisations from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Compte.
	 */
	public function getCotisationsJoinMembreRelatedByEnregistrePar($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ComptePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCotisations === null) {
			if ($this->isNew()) {
				$this->collCotisations = array();
			} else {

				$criteria->add(CotisationPeer::COMPTE_ID, $this->id);

				$this->collCotisations = CotisationPeer::doSelectJoinMembreRelatedByEnregistrePar($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CotisationPeer::COMPTE_ID, $this->id);

			if (!isset($this->lastCotisationCriteria) || !$this->lastCotisationCriteria->equals($criteria)) {
				$this->collCotisations = CotisationPeer::doSelectJoinMembreRelatedByEnregistrePar($criteria, $con, $join_behavior);
			}
		}
		$this->lastCotisationCriteria = $criteria;

		return $this->collCotisations;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Compte is new, it will return
	 * an empty collection; or if this Compte has previously
	 * been saved, it will retrieve related Cotisations from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Compte.
	 */
	public function getCotisationsJoinMembreRelatedByMisAJourPar($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ComptePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCotisations === null) {
			if ($this->isNew()) {
				$this->collCotisations = array();
			} else {

				$criteria->add(CotisationPeer::COMPTE_ID, $this->id);

				$this->collCotisations = CotisationPeer::doSelectJoinMembreRelatedByMisAJourPar($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CotisationPeer::COMPTE_ID, $this->id);

			if (!isset($this->lastCotisationCriteria) || !$this->lastCotisationCriteria->equals($criteria)) {
				$this->collCotisations = CotisationPeer::doSelectJoinMembreRelatedByMisAJourPar($criteria, $con, $join_behavior);
			}
		}
		$this->lastCotisationCriteria = $criteria;

		return $this->collCotisations;
	}

	/**
	 * Clears out the collDepenses collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addDepenses()
	 */
	public function clearDepenses()
	{
		$this->collDepenses = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collDepenses collection (array).
	 *
	 * By default this just sets the collDepenses collection to an empty array (like clearcollDepenses());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initDepenses()
	{
		$this->collDepenses = array();
	}

	/**
	 * Gets an array of Depense objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Compte has previously been saved, it will retrieve
	 * related Depenses from storage. If this Compte is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Depense[]
	 * @throws     PropelException
	 */
	public function getDepenses($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ComptePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collDepenses === null) {
			if ($this->isNew()) {
			   $this->collDepenses = array();
			} else {

				$criteria->add(DepensePeer::COMPTE_ID, $this->id);

				DepensePeer::addSelectColumns($criteria);
				$this->collDepenses = DepensePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(DepensePeer::COMPTE_ID, $this->id);

				DepensePeer::addSelectColumns($criteria);
				if (!isset($this->lastDepenseCriteria) || !$this->lastDepenseCriteria->equals($criteria)) {
					$this->collDepenses = DepensePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastDepenseCriteria = $criteria;
		return $this->collDepenses;
	}

	/**
	 * Returns the number of related Depense objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Depense objects.
	 * @throws     PropelException
	 */
	public function countDepenses(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ComptePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collDepenses === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(DepensePeer::COMPTE_ID, $this->id);

				$count = DepensePeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(DepensePeer::COMPTE_ID, $this->id);

				if (!isset($this->lastDepenseCriteria) || !$this->lastDepenseCriteria->equals($criteria)) {
					$count = DepensePeer::doCount($criteria, $con);
				} else {
					$count = count($this->collDepenses);
				}
			} else {
				$count = count($this->collDepenses);
			}
		}
		$this->lastDepenseCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a Depense object to this object
	 * through the Depense foreign key attribute.
	 *
	 * @param      Depense $l Depense
	 * @return     void
	 * @throws     PropelException
	 */
	public function addDepense(Depense $l)
	{
		if ($this->collDepenses === null) {
			$this->initDepenses();
		}
		if (!in_array($l, $this->collDepenses, true)) { // only add it if the **same** object is not already associated
			array_push($this->collDepenses, $l);
			$l->setCompte($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Compte is new, it will return
	 * an empty collection; or if this Compte has previously
	 * been saved, it will retrieve related Depenses from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Compte.
	 */
	public function getDepensesJoinAssociation($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ComptePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collDepenses === null) {
			if ($this->isNew()) {
				$this->collDepenses = array();
			} else {

				$criteria->add(DepensePeer::COMPTE_ID, $this->id);

				$this->collDepenses = DepensePeer::doSelectJoinAssociation($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(DepensePeer::COMPTE_ID, $this->id);

			if (!isset($this->lastDepenseCriteria) || !$this->lastDepenseCriteria->equals($criteria)) {
				$this->collDepenses = DepensePeer::doSelectJoinAssociation($criteria, $con, $join_behavior);
			}
		}
		$this->lastDepenseCriteria = $criteria;

		return $this->collDepenses;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Compte is new, it will return
	 * an empty collection; or if this Compte has previously
	 * been saved, it will retrieve related Depenses from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Compte.
	 */
	public function getDepensesJoinActivite($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ComptePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collDepenses === null) {
			if ($this->isNew()) {
				$this->collDepenses = array();
			} else {

				$criteria->add(DepensePeer::COMPTE_ID, $this->id);

				$this->collDepenses = DepensePeer::doSelectJoinActivite($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(DepensePeer::COMPTE_ID, $this->id);

			if (!isset($this->lastDepenseCriteria) || !$this->lastDepenseCriteria->equals($criteria)) {
				$this->collDepenses = DepensePeer::doSelectJoinActivite($criteria, $con, $join_behavior);
			}
		}
		$this->lastDepenseCriteria = $criteria;

		return $this->collDepenses;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Compte is new, it will return
	 * an empty collection; or if this Compte has previously
	 * been saved, it will retrieve related Depenses from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Compte.
	 */
	public function getDepensesJoinMembreRelatedByEnregistrePar($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ComptePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collDepenses === null) {
			if ($this->isNew()) {
				$this->collDepenses = array();
			} else {

				$criteria->add(DepensePeer::COMPTE_ID, $this->id);

				$this->collDepenses = DepensePeer::doSelectJoinMembreRelatedByEnregistrePar($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(DepensePeer::COMPTE_ID, $this->id);

			if (!isset($this->lastDepenseCriteria) || !$this->lastDepenseCriteria->equals($criteria)) {
				$this->collDepenses = DepensePeer::doSelectJoinMembreRelatedByEnregistrePar($criteria, $con, $join_behavior);
			}
		}
		$this->lastDepenseCriteria = $criteria;

		return $this->collDepenses;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Compte is new, it will return
	 * an empty collection; or if this Compte has previously
	 * been saved, it will retrieve related Depenses from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Compte.
	 */
	public function getDepensesJoinMembreRelatedByMisAJourPar($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ComptePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collDepenses === null) {
			if ($this->isNew()) {
				$this->collDepenses = array();
			} else {

				$criteria->add(DepensePeer::COMPTE_ID, $this->id);

				$this->collDepenses = DepensePeer::doSelectJoinMembreRelatedByMisAJourPar($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(DepensePeer::COMPTE_ID, $this->id);

			if (!isset($this->lastDepenseCriteria) || !$this->lastDepenseCriteria->equals($criteria)) {
				$this->collDepenses = DepensePeer::doSelectJoinMembreRelatedByMisAJourPar($criteria, $con, $join_behavior);
			}
		}
		$this->lastDepenseCriteria = $criteria;

		return $this->collDepenses;
	}

	/**
	 * Clears out the collRecettes collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addRecettes()
	 */
	public function clearRecettes()
	{
		$this->collRecettes = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collRecettes collection (array).
	 *
	 * By default this just sets the collRecettes collection to an empty array (like clearcollRecettes());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initRecettes()
	{
		$this->collRecettes = array();
	}

	/**
	 * Gets an array of Recette objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Compte has previously been saved, it will retrieve
	 * related Recettes from storage. If this Compte is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Recette[]
	 * @throws     PropelException
	 */
	public function getRecettes($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ComptePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRecettes === null) {
			if ($this->isNew()) {
			   $this->collRecettes = array();
			} else {

				$criteria->add(RecettePeer::COMPTE_ID, $this->id);

				RecettePeer::addSelectColumns($criteria);
				$this->collRecettes = RecettePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(RecettePeer::COMPTE_ID, $this->id);

				RecettePeer::addSelectColumns($criteria);
				if (!isset($this->lastRecetteCriteria) || !$this->lastRecetteCriteria->equals($criteria)) {
					$this->collRecettes = RecettePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastRecetteCriteria = $criteria;
		return $this->collRecettes;
	}

	/**
	 * Returns the number of related Recette objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Recette objects.
	 * @throws     PropelException
	 */
	public function countRecettes(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ComptePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collRecettes === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(RecettePeer::COMPTE_ID, $this->id);

				$count = RecettePeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(RecettePeer::COMPTE_ID, $this->id);

				if (!isset($this->lastRecetteCriteria) || !$this->lastRecetteCriteria->equals($criteria)) {
					$count = RecettePeer::doCount($criteria, $con);
				} else {
					$count = count($this->collRecettes);
				}
			} else {
				$count = count($this->collRecettes);
			}
		}
		$this->lastRecetteCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a Recette object to this object
	 * through the Recette foreign key attribute.
	 *
	 * @param      Recette $l Recette
	 * @return     void
	 * @throws     PropelException
	 */
	public function addRecette(Recette $l)
	{
		if ($this->collRecettes === null) {
			$this->initRecettes();
		}
		if (!in_array($l, $this->collRecettes, true)) { // only add it if the **same** object is not already associated
			array_push($this->collRecettes, $l);
			$l->setCompte($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Compte is new, it will return
	 * an empty collection; or if this Compte has previously
	 * been saved, it will retrieve related Recettes from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Compte.
	 */
	public function getRecettesJoinAssociation($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ComptePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRecettes === null) {
			if ($this->isNew()) {
				$this->collRecettes = array();
			} else {

				$criteria->add(RecettePeer::COMPTE_ID, $this->id);

				$this->collRecettes = RecettePeer::doSelectJoinAssociation($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(RecettePeer::COMPTE_ID, $this->id);

			if (!isset($this->lastRecetteCriteria) || !$this->lastRecetteCriteria->equals($criteria)) {
				$this->collRecettes = RecettePeer::doSelectJoinAssociation($criteria, $con, $join_behavior);
			}
		}
		$this->lastRecetteCriteria = $criteria;

		return $this->collRecettes;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Compte is new, it will return
	 * an empty collection; or if this Compte has previously
	 * been saved, it will retrieve related Recettes from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Compte.
	 */
	public function getRecettesJoinActivite($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ComptePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRecettes === null) {
			if ($this->isNew()) {
				$this->collRecettes = array();
			} else {

				$criteria->add(RecettePeer::COMPTE_ID, $this->id);

				$this->collRecettes = RecettePeer::doSelectJoinActivite($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(RecettePeer::COMPTE_ID, $this->id);

			if (!isset($this->lastRecetteCriteria) || !$this->lastRecetteCriteria->equals($criteria)) {
				$this->collRecettes = RecettePeer::doSelectJoinActivite($criteria, $con, $join_behavior);
			}
		}
		$this->lastRecetteCriteria = $criteria;

		return $this->collRecettes;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Compte is new, it will return
	 * an empty collection; or if this Compte has previously
	 * been saved, it will retrieve related Recettes from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Compte.
	 */
	public function getRecettesJoinMembreRelatedByEnregistrePar($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ComptePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRecettes === null) {
			if ($this->isNew()) {
				$this->collRecettes = array();
			} else {

				$criteria->add(RecettePeer::COMPTE_ID, $this->id);

				$this->collRecettes = RecettePeer::doSelectJoinMembreRelatedByEnregistrePar($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(RecettePeer::COMPTE_ID, $this->id);

			if (!isset($this->lastRecetteCriteria) || !$this->lastRecetteCriteria->equals($criteria)) {
				$this->collRecettes = RecettePeer::doSelectJoinMembreRelatedByEnregistrePar($criteria, $con, $join_behavior);
			}
		}
		$this->lastRecetteCriteria = $criteria;

		return $this->collRecettes;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Compte is new, it will return
	 * an empty collection; or if this Compte has previously
	 * been saved, it will retrieve related Recettes from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Compte.
	 */
	public function getRecettesJoinMembreRelatedByMisAJourPar($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ComptePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRecettes === null) {
			if ($this->isNew()) {
				$this->collRecettes = array();
			} else {

				$criteria->add(RecettePeer::COMPTE_ID, $this->id);

				$this->collRecettes = RecettePeer::doSelectJoinMembreRelatedByMisAJourPar($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(RecettePeer::COMPTE_ID, $this->id);

			if (!isset($this->lastRecetteCriteria) || !$this->lastRecetteCriteria->equals($criteria)) {
				$this->collRecettes = RecettePeer::doSelectJoinMembreRelatedByMisAJourPar($criteria, $con, $join_behavior);
			}
		}
		$this->lastRecetteCriteria = $criteria;

		return $this->collRecettes;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collCotisations) {
				foreach ((array) $this->collCotisations as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collDepenses) {
				foreach ((array) $this->collDepenses as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collRecettes) {
				foreach ((array) $this->collRecettes as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collCotisations = null;
		$this->collDepenses = null;
		$this->collRecettes = null;
			$this->aAssociation = null;
			$this->aMembreRelatedByEnregistrePar = null;
			$this->aMembreRelatedByMisAJourPar = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseCompte:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseCompte::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseCompte
