<?php use_helper('jQuery') ?>
<?php use_javascript('/pwCorePlugin/js/boxover/boxover.js') ?>
<?php use_javascript('/pwCorePlugin/js/jquery-tools/jquery.tools.min.js') ?>
<?php use_javascript('/pwCorePlugin/js/effects/deleteButton.js') ?>
<?php use_stylesheet('/pwCorePlugin/css/buttons.css') ?>
<?php use_stylesheet('/pwCorePlugin/css/form.css') ?>
<?php use_stylesheet('/pwCorePlugin/css/main.css') ?>
<?php use_stylesheet('/pwCorePlugin/css/menu.css') ?>
<?php use_stylesheet('/pwCorePlugin/css/overlay.css') ?>
<?php use_stylesheet('/pwCorePlugin/css/pagination.css') ?>
<?php use_stylesheet('/pwCorePlugin/css/table.css') ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <?php include_http_metas() ?>
  <?php include_metas() ?>
  <?php include_title() ?>
  <?php include_javascripts() ?>
  <?php include_stylesheets() ?>
  <link rel="shortcut icon" href="<?php echo $sf_request->getRelativeUrlRoot() ?>/pwCorePlugin/images/favicon.ico" />
</head>
<body>

  <div id="container">

    <!-- Header of the application -->

    <h1><?php echo sfContext::getInstance()->getUser()->getAssociationName('Piwam') ?></h1>

    <!-- Menu Part
         the menu is generated by the menus component,
         menu composition can be extended by app.yml -->

    <div id="menu">
      <?php if ($sf_user->getUserId()): ?>
      <div id="user_box">
          <p>
              Bonjour <span class="username"><?php echo $sf_user->getUsername() ?></span>
          </p>
          <?php echo link_to(image_tag('/pwCorePlugin/images/icons/user_edit') . ' Modifier mon profil', '@member_edit?id=' . $sf_user->getUserId()) ?>
          <?php echo link_to(image_tag('/pwCorePlugin/images/logout') . ' D&eacute;connexion', '@logout') ?>
      </div>
      <?php endif ?>
      <?php include_component('menus', 'generateMenu');?>
    </div>


    <!-- Main part of the content  -->

    <div id="content">
        <?php echo $sf_content ?>
    </div>
    <hr class="clear" />

  </div> <!-- container -->
</body>
</html>
