<?php

/**
 * Association
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    piwam
 * @subpackage model
 * @author     Adrien Mogenet
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class Association extends BaseAssociation
{
  /**
   * Ctor
   *
   * @param $table
   * @param $isNewEntry
   * @return unknown_type
   */
  public function __construct($table = null, $isNewEntry = false)
  {
    parent::__construct($table, $isNewEntry);
  }

  /**
   * Add all the default linked entities (Status, Activite...). This method
   * should be called when we register a new Association.
   */
  public function initialize()
  {
    $statutPresident = new Statut();
    $statutPresident->setState(ENABLED);
    $statutPresident->setAssociationId($this->getId());
    $statutPresident->setNom('Président');
    $statutPresident->save();

    $statutTresorier = new Statut();
    $statutTresorier->setActif(ENABLED);
    $statutTresorier->setAssociationId($this->getId());
    $statutTresorier->setNom('Trésorier');
    $statutTresorier->save();

    $statutSecretaire = new Statut();
    $statutSecretaire->setActif(ENABLED);
    $statutSecretaire->setAssociationId($this->getId());
    $statutSecretaire->setNom('Secrétaire');
    $statutSecretaire->save();

    $statutMembreActif = new Statut();
    $statutMembreActif->setActif(ENABLED);
    $statutMembreActif->setAssociationId($this->getId());
    $statutMembreActif->setNom('Membre actif');
    $statutMembreActif->save();

    $statutMembreDhonneur = new Statut();
    $statutMembreDhonneur->setActif(ENABLED);
    $statutMembreDhonneur->setAssociationId($this->getId());
    $statutMembreDhonneur->setNom('Membre d\'honneur');
    $statutMembreDhonneur->save();

    $activiteGeneral = new Activite();
    $activiteGeneral->setActif(ENABLED);
    $activiteGeneral->setLibelle("Fonctionnement général de l'association");
    $activiteGeneral->setAssociationId($this->getId());
    $activiteGeneral->save();

    $compteMonnaie = new Compte();
    $compteMonnaie->setAssociationId($this->getId());
    $compteMonnaie->setLibelle("Caisse de monnaie");
    $compteMonnaie->setReference("CAISSE_MONNAIE");
    $compteMonnaie->setActif(ENABLED);
    $compteMonnaie->save();
  }
}