<?php
/**
 * Member
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    piwam
 * @subpackage model
 * @author     Adrien Mogenet
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class Member extends BaseMember
{
  /**
   * Get Member object as string
   *
   * @return string
   */
  public function __toString()
  {
    return $this->getFirstname() . ' ' . $this->getLastname();
  }

  /**
   * Overrides the setPassword to encrypt it
   *
   * @param   string  $v
   * @return  Member  $this
   */
  public function setPassword($v)
  {
    return $this->_set('password', sha1($v));
  }

  /**
   * Overrides the setUsername method (manage the null case)
   *
   * @param   string  $v
   * @return  Member  $this
   */
  public function setUsername($v)
  {
    if ($v == "")
    {
      $v = null;
    }

    return $this->_set('username', $v);
  }

  /**
   * Returns the whole URI of user's picture, or 'no-picture' image
   * if he doesn't have one
   *
   * @return string
   */
  public function getPictureURI()
  {
    if ($this->getPicture())
    {
      return '/uploads/trombinoscope/' . $this->getPicture();
    }
    else
    {
      return 'no_picture';
    }
  }

  /**
   * Add a new credential to the member
   *
   * @param   string  $code   : Code of the AclAction
   */
  public function addCredential($code)
  {
    $credential = new AclCredential();
    $credential->setMemberId($this->getId());
    $credential->setAclAction(AclActionTable::getByCode($code));
    $credential->save();
  }

  /**
   *
   * @todo    implements
   * @return  boolean
   */
  public function hasToPayDue()
  {
    return false;
  }

  /**
   * Get the whole adress of the member
   *
   * @return string
   */
  public function getCompleteAddress()
  {
    return StringTools::to7bit($this->getStreet()) . ', ' . $this->getZipcode() . ' ' . StringTools::to7bit($this->getCity());
  }
}