<?php

/**
 * BaseDebt
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $member_id
 * @property integer $expense_id
 * @property Member $Member
 * @property Expense $Expense
 * 
 * @method integer getId()         Returns the current record's "id" value
 * @method integer getMemberId()   Returns the current record's "member_id" value
 * @method integer getExpenseId()  Returns the current record's "expense_id" value
 * @method Member  getMember()     Returns the current record's "Member" value
 * @method Expense getExpense()    Returns the current record's "Expense" value
 * @method Debt    setId()         Sets the current record's "id" value
 * @method Debt    setMemberId()   Sets the current record's "member_id" value
 * @method Debt    setExpenseId()  Sets the current record's "expense_id" value
 * @method Debt    setMember()     Sets the current record's "Member" value
 * @method Debt    setExpense()    Sets the current record's "Expense" value
 * 
 * @package    piwam
 * @subpackage model
 * @author     Adrien Mogenet
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDebt extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('piwampg_debt');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('member_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('expense_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Member', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Expense', array(
             'local' => 'expense_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}