<?php


/**
 * This class defines the structure of the 'piwam_membre' table.
 *
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Wed Nov 25 20:26:41 2009
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class MembreTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.MembreTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('piwam_membre');
		$this->setPhpName('Membre');
		$this->setClassname('Membre');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('NOM', 'Nom', 'VARCHAR', true, 255, null);
		$this->addColumn('PRENOM', 'Prenom', 'VARCHAR', true, 255, null);
		$this->addColumn('PSEUDO', 'Pseudo', 'VARCHAR', false, 255, null);
		$this->addColumn('PASSWORD', 'Password', 'VARCHAR', false, 255, null);
		$this->addForeignKey('STATUT_ID', 'StatutId', 'INTEGER', 'piwam_statut', 'ID', true, null, null);
		$this->addColumn('DATE_INSCRIPTION', 'DateInscription', 'DATE', true, null, null);
		$this->addColumn('EXEMPTE_COTISATION', 'ExempteCotisation', 'BOOLEAN', true, null, null);
		$this->addColumn('RUE', 'Rue', 'VARCHAR', false, 255, null);
		$this->addColumn('CP', 'Cp', 'VARCHAR', false, 8, null);
		$this->addColumn('VILLE', 'Ville', 'VARCHAR', false, 255, null);
		$this->addColumn('PAYS', 'Pays', 'VARCHAR', false, 8, null);
		$this->addColumn('PICTURE', 'Picture', 'VARCHAR', false, 255, null);
		$this->addColumn('EMAIL', 'Email', 'VARCHAR', false, 255, null);
		$this->addColumn('WEBSITE', 'Website', 'VARCHAR', false, 255, null);
		$this->addColumn('TEL_FIXE', 'TelFixe', 'VARCHAR', false, 16, null);
		$this->addColumn('TEL_PORTABLE', 'TelPortable', 'VARCHAR', false, 16, null);
		$this->addColumn('ACTIF', 'Actif', 'INTEGER', false, null, 1);
		$this->addForeignKey('ASSOCIATION_ID', 'AssociationId', 'INTEGER', 'piwam_association', 'ID', true, null, null);
		$this->addForeignKey('ENREGISTRE_PAR', 'EnregistrePar', 'INTEGER', 'piwam_membre', 'ID', false, null, null);
		$this->addForeignKey('MIS_A_JOUR_PAR', 'MisAJourPar', 'INTEGER', 'piwam_membre', 'ID', false, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Statut', 'Statut', RelationMap::MANY_TO_ONE, array('statut_id' => 'id', ), 'CASCADE', null);
    $this->addRelation('Association', 'Association', RelationMap::MANY_TO_ONE, array('association_id' => 'id', ), 'CASCADE', null);
    $this->addRelation('MembreRelatedByEnregistrePar', 'Membre', RelationMap::MANY_TO_ONE, array('enregistre_par' => 'id', ), 'CASCADE', null);
    $this->addRelation('MembreRelatedByMisAJourPar', 'Membre', RelationMap::MANY_TO_ONE, array('mis_a_jour_par' => 'id', ), 'CASCADE', null);
    $this->addRelation('AclCredential', 'AclCredential', RelationMap::ONE_TO_MANY, array('id' => 'membre_id', ), 'CASCADE', null);
    $this->addRelation('ActiviteRelatedByEnregistrePar', 'Activite', RelationMap::ONE_TO_MANY, array('id' => 'enregistre_par', ), 'CASCADE', null);
    $this->addRelation('ActiviteRelatedByMisAJourPar', 'Activite', RelationMap::ONE_TO_MANY, array('id' => 'mis_a_jour_par', ), 'CASCADE', null);
    $this->addRelation('AssociationRelatedByEnregistrePar', 'Association', RelationMap::ONE_TO_MANY, array('id' => 'enregistre_par', ), 'CASCADE', null);
    $this->addRelation('AssociationRelatedByMisAJourPar', 'Association', RelationMap::ONE_TO_MANY, array('id' => 'mis_a_jour_par', ), 'CASCADE', null);
    $this->addRelation('CompteRelatedByEnregistrePar', 'Compte', RelationMap::ONE_TO_MANY, array('id' => 'enregistre_par', ), 'CASCADE', null);
    $this->addRelation('CompteRelatedByMisAJourPar', 'Compte', RelationMap::ONE_TO_MANY, array('id' => 'mis_a_jour_par', ), 'CASCADE', null);
    $this->addRelation('CotisationRelatedByMembreId', 'Cotisation', RelationMap::ONE_TO_MANY, array('id' => 'membre_id', ), 'CASCADE', null);
    $this->addRelation('CotisationRelatedByEnregistrePar', 'Cotisation', RelationMap::ONE_TO_MANY, array('id' => 'enregistre_par', ), 'CASCADE', null);
    $this->addRelation('CotisationRelatedByMisAJourPar', 'Cotisation', RelationMap::ONE_TO_MANY, array('id' => 'mis_a_jour_par', ), 'CASCADE', null);
    $this->addRelation('CotisationTypeRelatedByEnregistrePar', 'CotisationType', RelationMap::ONE_TO_MANY, array('id' => 'enregistre_par', ), 'CASCADE', null);
    $this->addRelation('CotisationTypeRelatedByMisAJourPar', 'CotisationType', RelationMap::ONE_TO_MANY, array('id' => 'mis_a_jour_par', ), 'CASCADE', null);
    $this->addRelation('DepenseRelatedByEnregistrePar', 'Depense', RelationMap::ONE_TO_MANY, array('id' => 'enregistre_par', ), 'CASCADE', null);
    $this->addRelation('DepenseRelatedByMisAJourPar', 'Depense', RelationMap::ONE_TO_MANY, array('id' => 'mis_a_jour_par', ), 'CASCADE', null);
    $this->addRelation('MembreRelatedByEnregistrePar', 'Membre', RelationMap::ONE_TO_MANY, array('id' => 'enregistre_par', ), 'CASCADE', null);
    $this->addRelation('MembreRelatedByMisAJourPar', 'Membre', RelationMap::ONE_TO_MANY, array('id' => 'mis_a_jour_par', ), 'CASCADE', null);
    $this->addRelation('RecetteRelatedByEnregistrePar', 'Recette', RelationMap::ONE_TO_MANY, array('id' => 'enregistre_par', ), 'CASCADE', null);
    $this->addRelation('RecetteRelatedByMisAJourPar', 'Recette', RelationMap::ONE_TO_MANY, array('id' => 'mis_a_jour_par', ), 'CASCADE', null);
    $this->addRelation('StatutRelatedByEnregistrePar', 'Statut', RelationMap::ONE_TO_MANY, array('id' => 'enregistre_par', ), 'CASCADE', null);
    $this->addRelation('StatutRelatedByMisAJourPar', 'Statut', RelationMap::ONE_TO_MANY, array('id' => 'mis_a_jour_par', ), 'CASCADE', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // MembreTableMap
