<?php

/**
 * PluginMailTemplateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMailTemplateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMailTemplateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMailTemplate');
    }
}