<?php

/**
 * AclAction
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    piwam
 * @subpackage model
 * @author     Adrien Mogenet
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class PluginAclAction extends BaseAclAction
{
  private $_guardPermission = null;
  /**
   * Get cached sfGuardPermission
   * @return sfGuardGroup the group of rights
   */
  public function getPermissionGuard()
  {
    if($this->_guardPermission == null)
    {
      $this->_guardPermission = $this->getPermission();
    }
    return $this->_guardPermission;
  }
  public function getCode()
  {
    return $this->getPermissionGuard()->getName();
  }
  public function getLabel()
  {
    return $this->getPermissionGuard()->getDescription();
  }
}