<?php

/**
 * PluginDigitalDocumentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDigitalDocumentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDigitalDocumentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDigitalDocument');
    }
}