<?php

/**
 * PluginDebitTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDebitTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginDebitTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginDebit');
  }

  /**
   * Retrieve an unique debit by its id
   *
   * @param   integer       $id
   * @return  Debit
   */
  public static function getById($id)
  {
    $q = Doctrine_Query::create()
          ->from('Debit d')
          ->where('d.id = ?', $id);

    return $q->fetchOne();
  }

}