<?php
/**
 * Association
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    piwam
 * @subpackage model
 * @author     Adrien Mogenet
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class PluginAssociation extends BaseAssociation
{
  /**
   * Ctor
   *
   * @param $table
   * @param $isNewEntry
   * @return unknown_type
   */
  public function __construct($table = null, $isNewEntry = false)
  {
    parent::__construct($table, $isNewEntry);
  }

  /**
   * Add all the default linked entities (Status, Activite...). This method
   * should be called when we register a new Association.
   */
  public function initialize()
  {
    $id = $this->getId();
    
    StatusTable::add('Président', $id);
    StatusTable::add('Trésorier', $id);
    StatusTable::add('Secrétaire', $id);
    StatusTable::add('Membre actif', $id);
    StatusTable::add('Membre d\'honneur', $id);
    ActivityTable::add('Fonctionnement général de l\'association', $id);

    $this->_createStandardAccounts();
  }

  /**
   * Get the number of members who subscribed to the association
   *
   * @return integer
   */
  public function getNumberOfEnabledMembers()
  {
    $q = Doctrine_Query::create()
          ->select('m.id')
          ->from('Member m')
          ->where('m.association_id = ?', $this->getId())
          ->andWHere('m.state = ?', MemberTable::STATE_ENABLED);
    $n = $q->count();

    return ($n == null) ? 0 : $n;
  }

  /*
   * Register classicla bookkeeping accounts
   */
  private function _createStandardAccounts()
  {
    AccountTable::add(1,    null, 'Compte de capitaux',           $this->id);
    AccountTable::add(10,   1,    'Capital et réserves',          $this->id);
    AccountTable::add(101,  10,   "Capital",                      $this->id);
    AccountTable::add(1011, 101,  "Capital souscrit - non appelé", $this->id);
    AccountTable::add(1012, 101,  "Capital souscrit - appelé, non versé", $this->id);
    AccountTable::add(1013, 101,  "Capital souscrit - appelé, versé", $this->id);
    AccountTable::add(10131, 1013,"Capital non amorti",           $this->id);
    AccountTable::add(10131, 1013,  "Capital amorti",             $this->id);
    AccountTable::add(102,  10,   "Fonds fiduciaire",             $this->id);
    AccountTable::add(104,  10,   "Primes liées au capital social",$this->id);
    AccountTable::add(1041, 104,  "Primes d'émission",            $this->id);
    AccountTable::add(1042, 104,  "Primes de fusion",             $this->id);
    AccountTable::add(1043, 104,  "Primes d'apport",              $this->id);
    AccountTable::add(1044, 104,  "Primes de conversion d'obligations en actions", $this->id);
    AccountTable::add(1045, 104,  "Bons de souscription d'actions", $this->id);
    AccountTable::add(105,  10,   "Écart de réévaluation",        $this->id);
    AccountTable::add(1051, 105,  "Réserve spéciale de réévaluation", $this->id);
    AccountTable::add(1052, 105,  "Écart de réévaluation libre",  $this->id);
    AccountTable::add(1053, 105,  "Réserve spéciale de réévaluation", $this->id);
    AccountTable::add(1055, 105,  "Réserve de réévaluation (autres opérations légales)", $this->id);
    AccountTable::add(1057, 105,  "Autres écarts de réévaluation en France", $this->id);
    AccountTable::add(1058, 105,  "Autres écarts de réévaluation à l'étranger", $this->id);
    AccountTable::add(106,  10,   "Réserves",                     $this->id);
    AccountTable::add(1061, 106,  "Réserve légale",               $this->id);
    AccountTable::add(10611, 1061, "Réserve légale propre dite", $this->id);
    AccountTable::add(10612, 1061, "Plus-values nettes à long terme", $this->id);
    AccountTable::add(1062, 106,  "Réserves indisponibles",       $this->id);
    AccountTable::add(1063, 106,  "Réserves statutaires ou contractuelles", $this->id);
    AccountTable::add(1064, 106,  "Réserves réglementées",        $this->id);
    AccountTable::add(10641, 1064, "Plus-values nettes à long terme", $this->id);
    AccountTable::add(10643, 1064, "Réserves consécutives à l'octroi de subventions d'investissement", $this->id);
    AccountTable::add(10648, 1064, "Autres réserves réglementées", $this->id);
    AccountTable::add(1068, 106,  "Autres réserves",              $this->id);
    AccountTable::add(10681, 1068, "Réserve de propre assureur",  $this->id);
    AccountTable::add(10688, 1068, "Réserves diverses",           $this->id);
    AccountTable::add(107,  10,   "Écart d'équivalence",          $this->id);
    AccountTable::add(108,  10,   "Compte de l'exploitant",       $this->id);
    AccountTable::add(109,  10,   "Actionnaires : Capital souscrit - non appelé", $this->id);
    AccountTable::add(11,   1,    'Report à nouveau',             $this->id);
    AccountTable::add(110,  11,   'Report à nouveau (solde créditeur)', $this->id);
    AccountTable::add(119,  11,   'Report à nouveau (solde débiteur)', $this->id);
    AccountTable::add(12,   1,    "Résultat de l'exercice",       $this->id);
    AccountTable::add(120,  12,   "Résultat de l'exercice (bénéfice)", $this->id);
    AccountTable::add(129,  12,   "Résultat de l'exercice (perte)", $this->id);
    AccountTable::add(13,   1,    "Subventions d'investissement", $this->id);
    AccountTable::add(131,  13,   "Subventions d'équipement",     $this->id);
    AccountTable::add(138,  13,   "Autres subventions d'investissement", $this->id);
    AccountTable::add(139,  13,   "Subventions d'investissement inscrites au compte de résultat", $this->id);
    AccountTable::add(1391, 139,  "Subventions d'équipement",     $this->id);
    AccountTable::add(1398, 139,  "Autres subventions d'investissement", $this->id);
    AccountTable::add(14,   1,    "Provisions réglementées",      $this->id);
    AccountTable::add(142,  14,   "Provisions réglementées relatives aux immobilisations", $this->id);
    AccountTable::add(1423, 142,  "Provisions pour reconstitution des gisements miniers et pétroliers", $this->id);
    AccountTable::add(1424, 142,  "Provisions pour investissement (participation des salariés)", $this->id);
    AccountTable::add(143,  14,   "Provisions réglementées relatives aux stocks", $this->id);
    AccountTable::add(1431, 143,  "Hausse des prix",              $this->id);
    AccountTable::add(1432, 143,  "Fluctuation des cours",        $this->id);
    AccountTable::add(144,  14,   "Provisions réglementées relatives aux autres éléments de l'actif", $this->id);
    AccountTable::add(145,  14,   "Amortissements dérogatoires",  $this->id);
    AccountTable::add(146,  14,   "Provisions spéciales de réévaluation", $this->id);
    AccountTable::add(147,  14,   "Plus values réinvesties",      $this->id);
    AccountTable::add(148,  14,   "Autres provisions rélementées", $this->id);
    AccountTable::add(15,   1,    "Provisions",                   $this->id);
    AccountTable::add(151,  15,   "Provisions pour risques",      $this->id);
    AccountTable::add(1511, 151,  "Provisions pour litiges",      $this->id);
    AccountTable::add(1512, 151,  "Provisions pour garanties données aux clients", $this->id);
    AccountTable::add(1513, 151,  "Provisions pour pertes sur marchés à terme", $this->id);
    AccountTable::add(1514, 151,  "Provisions pour amendes et pénalités", $this->id);
    AccountTable::add(1515, 151,  "Provisions pour pertes de change", $this->id);
    AccountTable::add(1518, 151,  "Autres provisions pour risques", $this->id);
    AccountTable::add(151,  15,   "Provisions pour pensions et obligations similaires", $this->id);
    AccountTable::add(155,  15,   "Provisions pour impôts",       $this->id);
    AccountTable::add(156,  15,   "Provisions pour renouvellement des immobilisations", $this->id);
    AccountTable::add(157,  15,   "Provisions pour charges à répartir sur plusieurs exercices", $this->id);
    AccountTable::add(1572, 157,  "Provisions pour grosses réparations", $this->id);
    AccountTable::add(158,  16,   "Autres provisions pour charges", $this->id);
    AccountTable::add(1582, 15,   "Provisions pour charges sociales et fiscales sur congés à payer", $this->id);
    AccountTable::add(16,   1,    "Emprunts et dettes assimilées", $this->id);
    AccountTable::add(161,  16,   "Emprunts obligataires convertibles", $this->id);
    AccountTable::add(162,  16,   "Obligations représentatives de passifs nets remis en fiducie", $this->id);
    AccountTable::add(163,  16,   "Autres emprunts obligataires", $this->id);
    AccountTable::add(164,  16,   "Emprunts auprès des établissements de crédit", $this->id);
    AccountTable::add(165,  16,   "Dépôts et cautionnements reçus", $this->id);
    AccountTable::add(1651, 165,  "Dépôts",                       $this->id);
    AccountTable::add(1655, 165,  "Cautionnements",               $this->id);
    AccountTable::add(166,  16,   "Participation des salariés aux résultats", $this->id);
    AccountTable::add(1661, 166,  "Comptes bloqués",              $this->id);
    AccountTable::add(1662, 166,  "Fonds de participation",       $this->id);
    AccountTable::add(167,  16,   "Emprunts et dettes assortis de conditions particulières", $this->id);
    AccountTable::add(1671, 167,  "Émissions de titres participants", $this->id);
    AccountTable::add(1674, 167,  "Avances conditionnées de l'État", $this->id);
    AccountTable::add(1675, 167,  "Emprunts participants",        $this->id);
    AccountTable::add(168,  167,  "Autres emprunts et dettes assimilées", $this->id);
    AccountTable::add(1681, 168,  "Autres emprunts",              $this->id);
    AccountTable::add(1685, 168,  "Rentes viagères capitalisées", $this->id);
    AccountTable::add(1687, 168,  "Autres dettes",                $this->id);
    AccountTable::add(1688, 168,  "Intérêts courus",              $this->id);
    AccountTable::add(16881, 1688,"Sur emprunts obligataires convertibles", $this->id);
    AccountTable::add(16883, 1688,"Sur autres emprunts obligataires", $this->id);
    AccountTable::add(16884, 1688,"Sur emprunts auprès des établissements de crédit", $this->id);
    AccountTable::add(16885, 1688,"Sur dépôts et cautionnements reçus", $this->id);
    AccountTable::add(16886, 1688,"Sur participation des salariés aux résultats", $this->id);
    AccountTable::add(16887, 1688,"Sur emprunts et dettes assortis de conditions particulières", $this->id);
    AccountTable::add(16888, 1688,"Sur autres emprunts et dettes assimilées", $this->id);
    AccountTable::add(169,  16,   "Primes de remboursement des obligations", $this->id);
    AccountTable::add(17,   1,    "Dettes rattachées à des participations", $this->id);
    AccountTable::add(171,  17,   "Dettes rattachées à des participations (groupe)", $this->id);
    AccountTable::add(174,  17,   "Dettes rattachées à des participations (hors groupe)", $this->id);
    AccountTable::add(178,  17,   "Dettes rattachées à des sociétés en participation", $this->id);
    AccountTable::add(1781, 178,  "Principal",                    $this->id);
    AccountTable::add(1788, 178,  "Intérêts courus",              $this->id);
    AccountTable::add(18,   1,    "Comptes de liaison des établissements et sociétés en participation", $this->id);
    AccountTable::add(181,  18,   "Comptes de liaison des établissements", $this->id);
    AccountTable::add(186,  18,   "Biens et prestations de services échangés entre établissements (charges)", $this->id);
    AccountTable::add(187,  18,   "Biens et prestations de services échangés entre établissements (produits)", $this->id);
    AccountTable::add(188,  18,   "Comptes de liaison des sociétés en participation", $this->id);
    
    AccountTable::add(2,   null,  "Comptes d'immobilisations",    $this->id);
    AccountTable::add(20,   2,    "Immobilisations incorporelles",$this->id);
    AccountTable::add(21,   2,    "Immobilisations corporelles",  $this->id);
    AccountTable::add(22,   2,    "Immobilisations mises en concession", $this->id);
    AccountTable::add(23,   2,    "Immobilisations mises en concession", $this->id);
    AccountTable::add(27,   2,    "Autres immobilisations financières", $this->id);
    AccountTable::add(28,   2,    "Amortissements des immobilisations", $this->id);
    AccountTable::add(29,   2,    "Dépréciation des immobilisations", $this->id);

    AccountTable::add(3,    null, "Comptes de stock et en-cours", $this->id);
    AccountTable::add(31,   3,    "Matières premières (et fournitures)", $this->id);
    AccountTable::add(32,   3,    "Autres approvisionnements",    $this->id);
    AccountTable::add(33,   3,    "En-cours de production de biens", $this->id);
    AccountTable::add(34,   3,    "En-cours de production de services", $this->id);
    AccountTable::add(35,   3,    "Stocks",                       $this->id);
    AccountTable::add(37,   3,    "Stocks de marchandises",       $this->id);
    AccountTable::add(39,   3,    "Dépréciations des stocks et en-cours", $this->id);

    AccountTable::add(4,    null, "Comptes de tiers",             $this->id);
    AccountTable::add(40,   4,    "Fournisseurs et comptes rattachés", $this->id);
    AccountTable::add(41,   4,    "Clients et comptes rattachés", $this->id);
    AccountTable::add(42,   4,    "Personnel et comptes rattachés", $this->id);
    AccountTable::add(43,   4,    "Sécurité sociale et autres organismes sociaux", $this->id);
    AccountTable::add(44,   4,    "État et autres collectivités publiques", $this->id);
    AccountTable::add(47,   4,    "Comptes transitoires ou d'attente",  $this->id);
    AccountTable::add(48,   4,    "Comptes de régularisations",   $this->id);
    AccountTable::add(49,   4,    "Dépréciation des comptes de tiers", $this->id);

    AccountTable::add(5,    null, "Comptes financiers",           $this->id);
    AccountTable::add(50,   5,    "Valeurs mobilières de placement", $this->id);
    AccountTable::add(51,   5,    "Banques, établissements financiers et assimilés", $this->id);
    AccountTable::add(52,   5,    "Instruments de trésorerie",    $this->id);
    AccountTable::add(53,   5,    "Caisse",                       $this->id);
    AccountTable::add(54,   5,    "Règles d'avances et accréditifs", $this->id);
    AccountTable::add(58,   5,    "Virements internes",           $this->id);
    AccountTable::add(59,   5,    "Dépréciation des comptes financiers", $this->id);

    AccountTable::add(6,    null, "Comptes de charges",           $this->id);
    AccountTable::add(60,   6,    "Achats (sauf 603)",            $this->id);
    AccountTable::add(61,   6,    "Services extérieurs",          $this->id);
    AccountTable::add(62,   6,    "Autres services extérieurs",   $this->id);
    AccountTable::add(63,   6,    "Impôts, taxes et versements assimilés", $this->id);
    AccountTable::add(64,   6,    "Charges de personnel",         $this->id);
    AccountTable::add(67,   6,    "Charges exceptionnelles",      $this->id);
    AccountTable::add(68,   6,    "Dotations amortissements et provisions", $this->id);
    AccountTable::add(69,   6,    "Participation des salariés, impôts sur les bénéfices et assimilés", $this->id);

    AccountTable::add(7,    null, "Comptes de produits",          $this->id);
    AccountTable::add(70,   7,    "Ventes de produits fabriqués, de prestations de services, marchandises", $this->id);
    AccountTable::add(71,   7,    "Production stockée (ou destockage)", $this->id);
    AccountTable::add(72,   7,    "Production immobilisée",       $this->id);
    AccountTable::add(74,   7,    "Subventions d'exploitation",   $this->id);
    AccountTable::add(77,   7,    "Produits exceptionnels",       $this->id);
    AccountTable::add(78,   7,    "Reprises sur amortissements et provisions", $this->id);
    AccountTable::add(79,   7,    "Transferts de charges",        $this->id);
  }
}