<?php

/**
 * PluginSentMailTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSentMailTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginSentMailTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginSentMail');
  }
}