<?php
/**
 * Member
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    piwam
 * @subpackage model
 * @author     Adrien Mogenet
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class PluginMember extends BaseMember
{
  // cache sfUserGuard
  private $_guardUser = null;
  private $_guardUserModified = false;
  private $_guardIsNew = false;

  public function getUserGuard()
  {
    if($this->_guardUser == null)
    {
      $this->_guardUser = parent::getUser();
      // creation new member we create sfGuardUser
      if($this->_guardUser == null)
      {
        $this->_guardUser = new sfGuardUser();
        $this->_guardIsNew = true;
      }
    }
    return $this->_guardUser;
  }
  /**
   * Save guard user and copy the id generated
   * @param Doctrine_Event $event
   */
 /* public function preInsert($event)
  {
    $this->_guardUser->save();
    $this->setId($this->_guardUser->getId());
    parent::preInsert($event);
  }*/
  /**
   * Save guard user before save the current member
   * @param Doctrine_Connection $conn
   */
  public function save(Doctrine_Connection $conn = null)
  {

    if($this->getUserGuard()->isNew())
    {
      $username = $this->_guardUser->getUsername();
      // get id for member
      $this->_guardUser->save($conn);
      // FIX: Impossible get the id of sfUserGuard here !
      // the result of getId() is the firstname and lastname (equals toString()) 
      $user = $this->_guardUser;//
      sfContext::getInstance()->getLogger()->debug('save member '.$user->getFirstName().' id='.$user->getId());
      $user = sfGuardUserTable::getInstance()->retrieveByUsername($username);
      if($user == null)
      {
        throw new InvalidArgumentException("Save member but nothing sfGuardUser id can be read");
      }
      $this->setId($user->getId());
    }
    else if($this->_guardUserModified)
    {
      $this->_guardUser->save($conn);
    }
    parent::save($conn);
  }
  /*
   * GETTERS PROXY to sfGuardUser
   */
  /**
   * Get firstname from sfGuardUser
   */
  public function getFirstname()
  {
    return mb_convert_case($this->getUserGuard()->getFirstName(), MB_CASE_TITLE, "UTF8");
  }
  /**
   * Get lastname from sfGuardUser
   */
  public function getLastname()
  {
    return mb_convert_case($this->getUserGuard()->getLastName(), MB_CASE_TITLE, "UTF8");
  }
  /**
   * Get email from sfGuardUser
   */
  public function getEmail()
  {
    return $this->getUserGuard()->getEmailAddress();
  }
  /**
   * Get username from sfGuardUser
   */
  public function getUsername()
  {
    return $this->getUserGuard()->getUsername();
  }
  /**
   * Get password from sfGuardUser
   */
  public function getPassword()
  {
    return $this->getUserGuard()->getPassword();
  }
  /**
   * Get isSuperAdmin from sfGuardUser
   * <b>WARNING:</b> We can't set this value for Piwam, we need update database directly
   */
  public function isSuperAdmin()
  {
    return $this->getUserGuard()->getIsSuperAdmin();
  }
  /**
   * Get isActive from sfGuardUser
   */
  public function isActive()
  {
    return $this->getUserGuard()->getIsActive();
  }
  /**
   * Get firstname and last name from sfGuardUser
   */
  public function getName()
  {
    return mb_convert_case($this->getUserGuard()->getName(), MB_CASE_TITLE, "UTF8");
  }
  /*
   * SETTERS PROXY to sfGuardUser
   */
  public function setFirstname($val)
  {
    $this->_guardUserModified = true;
    $this->getUserGuard()->setFirstName($val);
    return $this;
  }
  public function setLastname($val)
  {
    $this->_guardUserModified = true;
    $this->getUserGuard()->setLastName($val);
    return $this;
  }
  public function setEmail($val)
  {
    $this->_guardUserModified = true;
    $this->getUserGuard()->setEmailAddress($val);
    return $this;
  }
  /**
   * Change state of user
   * @param integer $val
   */
  public function setState($val)
  {
    $this->_guardUserModified = true;
    if($val == MemberTable::STATE_ENABLED)
    {
      $this->getUserGuard()->setIsActive(true);
    }
    else
    {
      $this->getUserGuard()->setIsActive(false);
    }
    //parent::setState($val);
  }
  /*
   * SHORTCUTS for sfGuardUser
   */
  public function getAclGroupNames()
  {
    return $this->getUserGuard()->getGroupNames();
  }

  /**
   * Get Member object as string
   *
   * @return string
   */
  public function __toString()
  {
    return $this->getUserGuard()->getName();
  }

  /**
   * Overrides the setPassword to encrypt it
   *
   * @param   string  $v
   * @return  Member  $this
   */
  public function setPassword($v)
  {
    $this->_guardUserModified = true;
    $this->getUserGuard()->setPassword($v);
    return $this;
  }

  /**
   * Overrides the setUsername method (manage the null case)
   *
   * @param   string  $v
   * @return  Member  $this
   */
  public function setUsername($v)
  {
    $this->_guardUserModified = true;
    $this->getUserGuard()->setUsername($v);
    return $this;
  }

  /**
   * Returns the whole URI of user's picture, or 'no-picture' image
   * if he doesn't have one
   *
   * @return string
   */
  public function getPictureURI()
  {
    if ($this->getPicture())
    {
      return '/uploads/trombinoscope/' . $this->getPicture();
    }
    else
    {
      return 'no_picture';
    }
  }

  /**
   * Check if the member has to pay a due or not
   *
   * @return  boolean
   */
  public function hasToPayDue()
  {
    $days = $this->getDaysBeforeNextDue();

    if (null === $days)
    {
      return false;
    }
    else
    {
      return $days <= 0;
    }
  }

  /**
   * Get the number of days that the member get to pay his due.
   * If result a negative, it means that user should have paid
   * the Due X days ago.
   *
   * If the member does not have to pay due (exempted) null is
   * returned
   *
   * @return  Mixed   Null if non available, relative integer otherwise
   */
  public function getDaysBeforeNextDue()
  {
    if ($this->getDueExempt() == true)
    {
      return null;
    }
    else
    {
      $lastDue = DueTable::getLastForMember($this->getId());

      if (null == $lastDue)
      {
        $today = date('Y-m-d');
        $since = $this->getSubscriptionDate();

        return DateTools::getDaysBetween($today, $since);
      }
      else
      {
        return $lastDue->getDaysBeforeExpiration();
      }
    }
  }

  /**
   * Overrides getter for City field.
   *
   * @return  string  well-formated city
   */
  public function getCity()
  {
    return mb_convert_case($this->_get('city'), MB_CASE_UPPER, "UTF8");
  }

  /**
   * Overrides getter for Street field
   *
   * @return  string  well-formated street
   */
  public function getStreet()
  {
    return mb_convert_case($this->_get('street'), MB_CASE_TITLE, "UTF8");
  }
  
  /**
   * Get the whole adress of the member
   *
   * @return string
   */
  public function getCompleteAddress()
  {
    return StringTools::to7bit($this->getStreet()) . ', ' . $this->getZipcode() . ' ' . StringTools::to7bit($this->getCity());
  }

  /**
   * Returns information to display on Google Map
   *
   * @return  string
   */
  public function getInfoForGmap()
  {
    return '<b>' . $this->getName() . '</b><br/>' . $this->getStreet(). '<br/>' . $this->getStreet2(). '<br/>'
    .$this->getZipcode().' '. $this->getCity();
  }

  /**
   * Delete the Member object logically (it's not physically removed).
   * Erase username and passwords
   *
   * @return  Member
   */
  public function disable()
  {
    // $this->setUsername(null);
    //  $this->setPassword(null);
    $this->setState(MemberTable::STATE_DISABLED);
    
    return $this;
  }

  /**
   * Get the number of Dues paid by the Member
   *
   * @return  integer
   */
  public function getNumberOfDues()
  {
    $dues = $this->getDue();

    return count($dues);
  }
  /**
   * Return true if the user has geoloc position
   * @return boolean
   */
  public function hasGeolocAddress()
  {
    return $this->getLatitude() != null && $this->getLongitude() != null;
  }
  
  /**
   * Return ture if member has email set
   * @return boolean true if member has email
   */
  public function hasEmail()
  {
    $email = $this->getUserGuard()->getEmailAddress();
    return ($email != null && trim($email) != '');
  }
}