<?php
/**
 * PluginEntryTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEntryTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginEntryTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginEntry');
  }

  /**
   * Retrieve an unique debit by its id
   *
   * @param   integer       $id
   * @return  Entry
   */
  public static function getById($id)
  {
    $q = Doctrine_Query::create()
          ->from('Entry e')
          ->where('e.id = ?', $id);

    return $q->fetchOne();
  }

  /**
   * Retrieve the list of last entries recorded for the $associationId
   *
   * @param   integer       $associationId
   * @return  Doctrine_Collection
   */
  public static function getLastEntries($associationId)
  {
    $q = Doctrine_Query::create()
          ->from('Entry e')
          ->where('e.association_id = ?', $associationId)
          ->orderBy('e.date DESC')
          ->limit(20);

    return $q->execute();
  }
}