<?php

/**
 * PluginEntryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEntryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEntryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEntry');
    }
}