<?php

/**
 * PluginDocumentMetadataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDocumentMetadataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDocumentMetadataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDocumentMetadata');
    }
}