<?php

/**
 * PluginSentMailTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSentMailTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginSentMailTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginSentMail');
  }

  /**
   * Retrieve a paginated list of sent emails
   *
   * @param   integer         $page
   * @return  sfDoctrinePager
   */
  public static function getPaginatedSentMails($page = 1)
  {
    $q = Doctrine_Query::create()
          ->from('SentMail m')
          ->orderBy('m.created_at DESC');

    $pager = new sfDoctrinePager('SentMail', 20);
    $pager->setQuery($q);
    $pager->setPage($page);
    $pager->init();

    return $pager;
  }
}