<?php

/**
 * PluginPhysicalDocumentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPhysicalDocumentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPhysicalDocumentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPhysicalDocument');
    }
}