<?php

/**
 * PluginCreditTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCreditTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCreditTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCredit');
    }
}