<?php

/**
 * PluginEntry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginEntry extends BaseEntry
{
  /**
   * Get the amount of entry. Based on sum of credits, which is normally
   * equal to sum of debits
   */
  public function getAmount()
  {
    $q = Doctrine_Query::create()
          ->select('SUM(c.amount) AS total')
          ->from('Credit c')
          ->where('c.entry_id = ?', $this->getId());

    $row = $q->fetchArray();

    return ($row[0]['total'] !== null) ? $row[0]['total'] : 0;
  }
}