<?php

/**
 * Due
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    piwam
 * @subpackage model
 * @author     Adrien Mogenet
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class PluginDue extends BaseDue
{
  /**
   * Get the end date of validity of the Due, according to :
   *
   *   - the period (in months) if filled
   *   - the absolute end period otherwise
   *
   * @return  string    Date in YYY-mm-dd format
   * @since   1.2
   */
  public function getValidTill()
  {
    if ($this->getDueType()->getPeriod() >= 1)
    {
      $dateCalculator = new DateTools($this->getDate(), 'Y-m-d');
      $end_validity = $dateCalculator->add('mo', $this->getDueType()->getPeriod());
      
      return $end_validity;
    }
    else
    {
      return $this->getDueType()->getEndPeriod();
    }
  }

  /**
   * Return number of days before this Due expires. Result can
   * be negative if Due has already expired
   *
   * @return  integer
   * @since   1.2
   */
  public function getDaysBeforeExpiration()
  {
    $today = date('Y-m-d');

    return DateTools::getDaysBetween($today, $this->getValidTill());
  }
}