<?php
/**
 * Account
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    piwam
 * @subpackage model
 * @author     Adrien Mogenet
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class PluginAccount extends BaseAccount
{
  /**
   * Returns current Account as a string
   *
   * @return string
   */
  public function __toString()
  {
    return $this->getLabel();
  }

  /**
   * Returns true if Account has any child
   *
   * @return  boolean
   */
  public function hasChilds()
  {
    return (count($this->getChildAccounts()) !== 0);
  }

  /**
   * Shortcut to call getChildAccounts()
   *
   * @return Doctrine_Collection
   */
  public function getChilds()
  {
    return $this->getChildAccounts();
  }
}