<?php

/**
 * PluginDocumentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDocumentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDocumentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDocument');
    }
}