<?php

/**
 * PluginEventSubscriptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEventSubscriptionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEventSubscriptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEventSubscription');
    }
}