<?php

/**
 * MemberExtraValue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    piwam
 * @subpackage model
 * @author     Adrien Mogenet
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class MemberExtraValue extends BaseMemberExtraValue
{
}
