<?php
/**
 * MemberExtraRow
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    piwam
 * @subpackage model
 * @author     Adrien Mogenet
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class MemberExtraRow extends BaseMemberExtraRow
{
  /**
   * Parse the 'type' field in Database and return the real
   * type. (ie: `string 123 => string`)
   */
  public function getType()
  {
    $original = $this->__get('type');
    $split = explode(' ', $original);

    return $split[0];
  }
}
